"use client";

import Link from "next/link";
import { useParams } from "next/navigation";
import { useCallback, useEffect, useState } from "react";
import {
  getIssue,
  updateIssue,
  listCases,
  addIssueToCase,
  kindLabel,
  SEVERITY_TOKENS,
  STATUS_TOKENS,
  type IssueDetail,
  type CaseRow,
} from "@/lib/api/investigation";
import {
  glassStyle,
  Badge,
  OriginChip,
  InvestigationTabBar,
  EditableSection,
  EmptyState,
  fmtTs,
  splitVerdict,
  verdictTone,
} from "@/components/investigation/ui";

/**
 * Investigation → Issue detail (v0.1.7 — full-width, tabbed layout).
 *
 * Header (title + verdict banner + status/severity/case controls) over a
 * tabbed body: Overview (summary · scope · recommendations), Assessment
 * (conclusions · next steps), Activity (the issue_events timeline), and
 * Attack chain (the SVG causality diagram — stubbed here, generated by the
 * diagramming skill in v0.1.8). Operator-editable fields are what the agent
 * fills via issue_update; the timeline is what it appended via issue_add_event.
 */

const STATUSES = ["open", "investigating", "resolved", "closed"];
const SEVERITIES = ["low", "medium", "high", "critical"];

type Tab = "overview" | "assessment" | "activity" | "chain";
const TABS: { key: Tab; label: string; icon: string }[] = [
  { key: "overview", label: "Overview", icon: "dashboard" },
  { key: "assessment", label: "Assessment", icon: "gavel" },
  { key: "activity", label: "Activity", icon: "timeline" },
  { key: "chain", label: "Attack chain", icon: "account_tree" },
];

const EVENT_ICONS: Record<string, string> = {
  action: "bolt",
  finding: "search_insights",
  note: "sticky_note_2",
  conversation: "forum",
};

export default function IssueDetailPage() {
  const params = useParams<{ id: string }>();
  const id = params.id;
  const [issue, setIssue] = useState<IssueDetail | null>(null);
  const [cases, setCases] = useState<CaseRow[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [tab, setTab] = useState<Tab>("overview");
  const [regenerating, setRegenerating] = useState(false);

  // `silent` skips the full-page spinner — used for patch-triggered refetches
  // so editing a field doesn't flash the loading state. The initial mount (and
  // inter-issue navigation, which reuses this component with a new id) loads
  // non-silently so we never show one issue's content under another's id.
  const load = useCallback(async (silent = false) => {
    if (!silent) setLoading(true);
    setError(null);
    try {
      const [det, cl] = await Promise.all([getIssue(id), listCases()]);
      setIssue(det);
      setCases(cl.cases);
    } catch (e) {
      setError(e instanceof Error ? e.message : "failed to load issue");
    } finally {
      setLoading(false);
    }
  }, [id]);

  useEffect(() => {
    load();
  }, [load]);

  const patch = async (body: Parameters<typeof updateIssue>[1]) => {
    if (!issue) return;
    try {
      await updateIssue(id, body);
      load(true);
    } catch (e) {
      setError(e instanceof Error ? e.message : "update failed");
    }
  };

  // Regenerate the attack-chain SVG: fire a one-shot agent job (reuses the
  // scheduler — the agent reads the issue, draws the chain via the
  // svg_attack_chain skill, and stores it with issue_set_attack_chain), then
  // poll the issue until the SVG changes. Heavy op (a full agent turn), so we
  // poll up to ~3 min and show a spinner.
  const regenerate = async () => {
    if (!issue || regenerating) return;
    setRegenerating(true);
    const before = issue.attack_chain_svg ?? "";
    try {
      await fetch("/api/agent/jobs", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          name: `regen-diagram-${id}`,
          cron: "* * * * *",
          timezone: "UTC",
          run_once: true,
          enabled: true,
          bypass_approvals: true,
          action: {
            type: "prompt",
            skill: "svg_attack_chain",
            message:
              `Regenerate the attack-chain diagram for Guardian Issue ${id}. ` +
              `First call issue_get(issue_id="${id}") to read the investigation ` +
              `(summary, conclusions, activity timeline). Then, per the ` +
              `svg_attack_chain skill, draw a self-contained SVG of the attack's ` +
              `causal path and store it with issue_set_attack_chain(issue_id="${id}", ` +
              `svg="<the full svg>"). Do only this — do not change any other field.`,
          },
        }),
      });
      const deadline = Date.now() + 180_000;
      while (Date.now() < deadline) {
        await new Promise((r) => setTimeout(r, 5000));
        try {
          const det = await getIssue(id);
          if (det.attack_chain_svg && (det.attack_chain_svg ?? "") !== before) {
            setIssue(det);
            break;
          }
        } catch {
          /* transient — keep polling */
        }
      }
    } catch (e) {
      setError(e instanceof Error ? e.message : "regenerate failed");
    } finally {
      setRegenerating(false);
    }
  };

  if (loading) return <p className="text-sm text-on-surface-variant p-8 text-center">Loading…</p>;
  if (error) return <p className="text-sm text-error p-8 text-center">{error}</p>;
  if (!issue) return <p className="text-sm text-on-surface-variant p-8 text-center">Issue not found.</p>;

  const { verdict } = splitVerdict(issue.summary);

  return (
    <div className="max-w-[1400px] mx-auto px-8 py-8 pb-32">
      <Link href="/investigation/issues" className="text-xs text-on-surface-variant hover:text-on-surface inline-flex items-center gap-1 mb-4">
        <span className="material-symbols-outlined text-[16px]">arrow_back</span> Issues
      </Link>

      {/* Header */}
      <div className="rounded-2xl p-6 mb-6" style={glassStyle}>
        <div className="flex items-start gap-4">
          <span className="material-symbols-outlined text-2xl text-primary mt-0.5">report</span>
          <div className="flex-1 min-w-0">
            <h1 className="font-headline text-2xl font-bold tracking-tight text-on-surface">{issue.title}</h1>
            <div className="flex flex-wrap items-center gap-2 mt-2">
              <Badge tone={STATUS_TOKENS[issue.status]}>{issue.status}</Badge>
              <Badge tone={SEVERITY_TOKENS[issue.severity]}>{issue.severity}</Badge>
              <Badge>{kindLabel(issue.kind)}</Badge>
              <OriginChip origin={issue.origin} />
              {issue.source_ref && (
                <span className="inline-flex items-center gap-0.5 text-[11px] text-on-surface-variant">
                  <span className="material-symbols-outlined text-[14px]">tag</span>XSOAR {issue.source_ref}
                </span>
              )}
              <span className="text-[11px] text-on-surface-variant/60">updated {fmtTs(issue.updated_at)}</span>
            </div>
          </div>
        </div>

        {/* Verdict banner (derived from the summary's leading VERDICT: line) */}
        {verdict && (
          <div className={`mt-4 rounded-xl border px-4 py-2.5 flex items-center gap-2 ${verdictTone(verdict)}`}>
            <span className="material-symbols-outlined text-[18px]">gavel</span>
            <span className="text-sm font-medium">{verdict}</span>
          </div>
        )}

        {/* Control bar */}
        <div className="flex flex-wrap items-center gap-x-6 gap-y-3 mt-5 pt-5 border-t border-white/10">
          <Control label="Status">
            <select
              value={issue.status}
              onChange={(e) => patch({ status: e.target.value as IssueDetail["status"] })}
              className={`rounded-lg px-3 py-1.5 text-xs font-medium border bg-surface-container-high ${STATUS_TOKENS[issue.status] ?? ""}`}
            >
              {STATUSES.map((s) => <option key={s} value={s}>{s}</option>)}
            </select>
          </Control>
          <Control label="Severity">
            <select
              value={issue.severity}
              onChange={(e) => patch({ severity: e.target.value as IssueDetail["severity"] })}
              className={`rounded-lg px-3 py-1.5 text-xs font-medium border bg-surface-container-high ${SEVERITY_TOKENS[issue.severity] ?? ""}`}
            >
              {SEVERITIES.map((s) => <option key={s} value={s}>{s}</option>)}
            </select>
          </Control>
          <Control label="Case">
            <CaseAssigner issue={issue} cases={cases} onAssigned={load} />
          </Control>
          {/* Manual analyst actions live here (v0.1.7 placeholder — wired in a later release). */}
          <div className="ml-auto flex items-center gap-2 opacity-50">
            <button
              type="button"
              disabled
              title="Manual analyst actions — coming soon"
              className="inline-flex items-center gap-1.5 rounded-lg border border-outline-variant px-3 py-1.5 text-xs text-on-surface-variant cursor-not-allowed"
            >
              <span className="material-symbols-outlined text-[16px]">bolt</span>
              Actions
            </button>
          </div>
        </div>
      </div>

      {/* Tabs */}
      <InvestigationTabBar tabs={TABS} active={tab} onChange={setTab} />

      {tab === "overview" && (
        <div className="grid grid-cols-1 gap-4">
          <EditableSection icon="summarize" label="Summary" value={issue.summary ?? ""} onSave={(v) => patch({ summary: v })} />
          <EditableSection icon="center_focus_strong" label="Scope" value={issue.scope ?? ""} onSave={(v) => patch({ scope: v })} />
          <EditableSection icon="lightbulb" label="Recommendations" value={issue.recommendations ?? ""} onSave={(v) => patch({ recommendations: v })} />
        </div>
      )}

      {tab === "assessment" && (
        <div className="grid grid-cols-1 gap-4">
          <EditableSection icon="gavel" label="Conclusions" value={issue.conclusions ?? ""} onSave={(v) => patch({ conclusions: v })} />
          <EditableSection icon="checklist" label="Next steps" value={issue.next_steps ?? ""} onSave={(v) => patch({ next_steps: v })} />
        </div>
      )}

      {tab === "activity" && (
        <div>
          {issue.events.length === 0 ? (
            <EmptyState icon="timeline" title="No activity yet" hint="As Guardian investigates, each step and finding appears here as a timeline entry." />
          ) : (
            <ol className="space-y-3">
              {issue.events.map((ev) => (
                <li key={ev.id} className="flex gap-3 rounded-2xl p-4" style={glassStyle}>
                  <span className="h-8 w-8 rounded-full bg-surface-container-highest border border-primary/40 flex items-center justify-center shrink-0 text-primary">
                    <span className="material-symbols-outlined text-[16px]">{EVENT_ICONS[ev.type] ?? "circle"}</span>
                  </span>
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-2 text-[11px] text-on-surface-variant">
                      <span className="font-bold uppercase tracking-wide">{ev.type}</span>
                      <span className="text-on-surface-variant/60">{fmtTs(ev.ts)}</span>
                    </div>
                    <p className="text-sm text-on-surface whitespace-pre-wrap mt-1 leading-relaxed">{ev.content}</p>
                  </div>
                </li>
              ))}
            </ol>
          )}
        </div>
      )}

      {tab === "chain" && (
        issue.attack_chain_svg ? (
          <div className="rounded-2xl p-5" style={glassStyle}>
            <div className="flex items-center justify-between mb-3">
              <h3 className="text-xs font-bold uppercase tracking-widest text-on-surface flex items-center gap-2">
                <span className="material-symbols-outlined text-[18px] text-on-surface-variant">account_tree</span>
                Attack chain
              </h3>
              <button
                onClick={regenerate}
                disabled={regenerating}
                className="inline-flex items-center gap-1 text-[11px] text-primary hover:underline disabled:opacity-50"
              >
                <span className="material-symbols-outlined text-[14px]">{regenerating ? "hourglass_top" : "refresh"}</span>
                {regenerating ? "Regenerating… (≈1 min)" : "Regenerate"}
              </button>
            </div>
            {/* Rendered sandboxed as an <img> data-URI — SVG-in-img never
                executes script, so agent-produced markup can't run code. */}
            <div className="rounded-xl overflow-hidden bg-surface-container-lowest border border-outline-variant">
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img
                src={`data:image/svg+xml;utf8,${encodeURIComponent(issue.attack_chain_svg)}`}
                alt="Attack chain diagram"
                className="w-full h-auto block"
              />
            </div>
          </div>
        ) : (
          <EmptyState
            icon="account_tree"
            title="No attack chain yet"
            hint="Guardian draws the causality / attack chain when it resolves an investigation. You can also generate it now (a full agent pass — takes about a minute)."
          >
            <button
              onClick={regenerate}
              disabled={regenerating}
              className="mt-3 inline-flex items-center gap-1.5 rounded-xl bg-primary text-on-primary px-4 py-2 text-sm font-medium hover:opacity-90 transition disabled:opacity-50"
            >
              <span className="material-symbols-outlined text-[18px]">{regenerating ? "hourglass_top" : "auto_awesome"}</span>
              {regenerating ? "Generating… (≈1 min)" : "Generate diagram"}
            </button>
          </EmptyState>
        )
      )}
    </div>
  );
}

function Control({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <div className="flex items-center gap-2">
      <label className="text-[10px] uppercase tracking-widest text-on-surface-variant">{label}</label>
      {children}
    </div>
  );
}

function CaseAssigner({ issue, cases, onAssigned }: { issue: IssueDetail; cases: CaseRow[]; onAssigned: () => void }) {
  const assign = async (caseId: string) => {
    if (!caseId) return;
    await addIssueToCase(caseId, issue.id);
    onAssigned();
  };
  return issue.case ? (
    <Link
      href={`/investigation/cases/${issue.case.id}`}
      className="inline-flex items-center gap-1 text-xs text-secondary hover:underline rounded-lg border border-secondary/40 bg-secondary-container/30 px-3 py-1.5"
    >
      <span className="material-symbols-outlined text-[14px]">folder</span>
      {issue.case.title}
    </Link>
  ) : (
    <select
      defaultValue=""
      onChange={(e) => assign(e.target.value)}
      className="rounded-lg px-3 py-1.5 text-xs border border-outline-variant text-on-surface-variant bg-surface-container-high"
    >
      <option value="">unassigned…</option>
      {cases.map((c) => <option key={c.id} value={c.id}>{c.title}</option>)}
    </select>
  );
}
