"use client";

import Link from "next/link";
import { useParams } from "next/navigation";
import { useCallback, useEffect, useMemo, useState } from "react";
import { MarkdownContent } from "@/components/markdown-content";
import {
  getIssue,
  updateIssue,
  listCases,
  listIndicators,
  addIssueToCase,
  kindLabel,
  SEVERITY_TOKENS,
  STATUS_TOKENS,
  type IssueDetail,
  type CaseRow,
  type Indicator,
  type TechniqueMapping,
} from "@/lib/api/investigation";
import {
  glassStyle,
  Badge,
  OriginChip,
  InvestigationTabBar,
  EditableSection,
  EmptyState,
  IndicatorRow,
  DiagramTab,
  kindLayout,
  fmtTs,
  splitVerdict,
  verdictTone,
} from "@/components/investigation/ui";

/**
 * Investigation → Issue detail (v0.1.7 — full-width, tabbed layout).
 *
 * Header (title + verdict banner + status/severity/case controls) over a
 * tabbed body: Overview (summary · scope · recommendations), Assessment
 * (conclusions · next steps), Activity (the issue_events timeline), and
 * Attack chain (the SVG causality diagram — stubbed here, generated by the
 * diagramming skill in v0.1.8). Operator-editable fields are what the agent
 * fills via issue_update; the timeline is what it appended via issue_add_event.
 */

const STATUSES = ["open", "investigating", "resolved", "closed"];
const SEVERITIES = ["low", "medium", "high", "critical"];

type Tab = "overview" | "assessment" | "report" | "indicators" | "activity" | "chain" | "relations";
const TABS: { key: Tab; label: string; icon: string }[] = [
  { key: "overview", label: "Overview", icon: "dashboard" },
  { key: "assessment", label: "Assessment", icon: "gavel" },
  { key: "report", label: "Report", icon: "description" },
  { key: "indicators", label: "Indicators", icon: "fingerprint" },
  { key: "activity", label: "Activity", icon: "timeline" },
  { key: "chain", label: "Attack chain", icon: "account_tree" },
  { key: "relations", label: "Relations", icon: "hub" },
];

const EVENT_ICONS: Record<string, string> = {
  action: "bolt",
  finding: "search_insights",
  note: "sticky_note_2",
  conversation: "forum",
};

/**
 * #INV-F9 — look for a fresh `issue_diagram_rejected` audit row for this
 * issue + diagram surface, emitted by the MCP when _clean_svg rejects the
 * agent's SVG (e.g. >256 KB). Returns the rejection's code + size when found
 * after `sinceMs`, so the regenerate poll can show the real reason instead of
 * the generic "timed out — the agent run may have failed" message. Best-effort:
 * any error returns null (fall through to the generic message).
 */
async function findRecentDiagramRejection(
  issueId: string,
  diagram: "attack_chain" | "relations",
  sinceMs: number,
): Promise<{ code?: string; bytes?: number } | null> {
  try {
    const r = await fetch(
      `/api/agent/audit?action=issue_diagram_rejected&target=${encodeURIComponent(
        `issue:${issueId}`,
      )}&limit=10`,
      { cache: "no-store" },
    );
    if (!r.ok) return null;
    const data = (await r.json()) as {
      events?: Array<{
        ts?: string;
        metadata?: Record<string, unknown>;
        meta?: Record<string, unknown>;
      }>;
    };
    for (const ev of data.events ?? []) {
      const m = ev.metadata ?? ev.meta ?? {};
      if (m["diagram"] !== diagram) continue;
      // Only honor rejections at-or-after this regenerate run started, so a
      // stale rejection from a prior attempt doesn't mask a fresh timeout.
      const tsMs = ev.ts ? Date.parse(ev.ts) : NaN;
      if (!Number.isNaN(tsMs) && tsMs + 1000 < sinceMs) continue;
      return {
        code: typeof m["code"] === "string" ? (m["code"] as string) : undefined,
        bytes: typeof m["bytes"] === "number" ? (m["bytes"] as number) : undefined,
      };
    }
    return null;
  } catch {
    return null;
  }
}

export default function IssueDetailPage() {
  const params = useParams<{ id: string }>();
  const id = params.id;
  const [issue, setIssue] = useState<IssueDetail | null>(null);
  const [cases, setCases] = useState<CaseRow[]>([]);
  const [issueIndicators, setIssueIndicators] = useState<Indicator[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [tab, setTab] = useState<Tab>("overview");
  // null = idle; otherwise the diagram kind currently regenerating (only one at a time).
  const [regenerating, setRegenerating] = useState<null | "chain" | "relations">(null);
  // v0.2.45 — true while a one-shot report-generation agent job is in flight.
  const [genReport, setGenReport] = useState(false);
  const [actType, setActType] = useState("all");
  const [actSort, setActSort] = useState<"oldest" | "newest">("oldest");

  // `silent` skips the full-page spinner — used for patch-triggered refetches
  // so editing a field doesn't flash the loading state. The initial mount (and
  // inter-issue navigation, which reuses this component with a new id) loads
  // non-silently so we never show one issue's content under another's id.
  const load = useCallback(async (silent = false) => {
    if (!silent) setLoading(true);
    setError(null);
    try {
      const [det, cl, inds] = await Promise.all([
        getIssue(id),
        listCases(),
        listIndicators({ issue_id: id }),
      ]);
      setIssue(det);
      setCases(cl.cases);
      setIssueIndicators(inds.indicators);
    } catch (e) {
      setError(e instanceof Error ? e.message : "failed to load issue");
    } finally {
      setLoading(false);
    }
  }, [id]);

  useEffect(() => {
    load();
  }, [load]);

  const patch = async (body: Parameters<typeof updateIssue>[1]) => {
    if (!issue) return;
    try {
      await updateIssue(id, body);
      load(true);
    } catch (e) {
      setError(e instanceof Error ? e.message : "update failed");
    }
  };

  // Regenerate a diagram on demand: fire a one-shot agent job (reuses the
  // scheduler — the agent reads the issue and draws the SVG via the matching
  // skill, then stores it with the matching tool), then poll the issue until
  // the relevant SVG field changes. Heavy op (a full agent turn), so we poll
  // up to ~3 min and show a spinner. One code path drives both diagram kinds —
  // only the skill, the storage tool, and the watched field differ.
  const regenerate = async (kind: "chain" | "relations") => {
    if (!issue || regenerating) return;
    setRegenerating(kind);
    const isChain = kind === "chain";
    const before = (isChain ? issue.attack_chain_svg : issue.relations_canvas_svg) ?? "";
    const skill = isChain ? "svg_attack_chain" : "svg_relation_graph";
    const message = isChain
      ? `Regenerate the attack-chain diagram for Guardian Issue ${id}. ` +
        `First call issue_get(issue_id="${id}") to read the investigation ` +
        `(summary, conclusions, activity timeline). Then, per the ` +
        `svg_attack_chain skill, draw a self-contained SVG of the attack's ` +
        `causal path and store it with issue_set_attack_chain(issue_id="${id}", ` +
        `svg="<the full svg>"). Do only this — do not change any other field.`
      : `Regenerate the STIX relations canvas for Guardian Issue ${id}. ` +
        `First call indicators_list(issue_id="${id}"), then indicator_get(id) for ` +
        `each indicator to read its relationships. Where obvious edges are missing ` +
        `(domain resolves-to ip, indicator indicates malware / uses a technique / ` +
        `attributed-to an actor), record them first with indicator_relate. Then, ` +
        `per the svg_relation_graph skill, draw a self-contained layered SVG of the ` +
        `indicators and their STIX relationships and store it with ` +
        `issue_set_relation_graph(issue_id="${id}", svg="<the full svg>"). ` +
        `Do only this — do not change any other field.`;
    try {
      // A unique suffix avoids colliding with a prior one-shot job of the same
      // name (which the scheduler 400s on) — the deterministic name was the
      // v0.2.3 silent-spinner trigger.
      const resp = await fetch("/api/agent/jobs", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          name: `regen-${kind}-${id}-${before.length}`,
          cron: "* * * * *",
          timezone: "UTC",
          run_once: true,
          enabled: true,
          bypass_approvals: true,
          action: { type: "prompt", skill, message },
        }),
      });
      // fetch() does NOT throw on 4xx/5xx — check explicitly so a failed job
      // surfaces an error instead of a silent 3-minute poll to the deadline.
      if (!resp.ok) {
        const detail = await resp.json().catch(() => ({}));
        throw new Error((detail as { error?: string })?.error ?? `regenerate failed (${resp.status})`);
      }
      const pollStartedMs = Date.now();
      const deadline = pollStartedMs + 180_000;
      let updated = false;
      while (Date.now() < deadline) {
        await new Promise((r) => setTimeout(r, 5000));
        try {
          const det = await getIssue(id);
          const now = (isChain ? det.attack_chain_svg : det.relations_canvas_svg) ?? "";
          if (now && now !== before) {
            setIssue(det);
            updated = true;
            break;
          }
        } catch {
          /* transient — keep polling */
        }
      }
      // On deadline exit, refresh to the latest state and tell the operator
      // rather than silently dropping the spinner.
      if (!updated) {
        try { setIssue(await getIssue(id)); } catch { /* ignore */ }
        // #INV-F9 — distinguish a too-large-SVG REJECTION from a generic
        // agent-run failure/timeout. The MCP emits an `issue_diagram_rejected`
        // audit row (target=issue:<id>) when _clean_svg rejects the agent's
        // diagram (e.g. >256 KB). If we find a fresh one for this surface, tell
        // the operator the actual reason instead of the vague timeout message.
        const reject = await findRecentDiagramRejection(
          id,
          isChain ? "attack_chain" : "relations",
          pollStartedMs,
        );
        if (reject?.code === "svg_too_large") {
          const kb = reject.bytes ? ` (${Math.round(reject.bytes / 1024)} KB; cap 256 KB)` : "";
          setError(
            `The agent produced a diagram that was too large to store${kb}. ` +
              "Ask it to simplify the diagram (fewer nodes/labels) and regenerate.",
          );
        } else if (reject) {
          setError(
            `The agent's diagram was rejected (${reject.code ?? "invalid svg"}). ` +
              "Try regenerating.",
          );
        } else {
          setError("Regenerate timed out — the diagram may not have updated (the agent run may have failed). Try again.");
        }
      }
    } catch (e) {
      setError(e instanceof Error ? e.message : "regenerate failed");
    } finally {
      setRegenerating(null);
    }
  };

  // v0.2.45 — generate (or refresh) the structured investigation report on
  // demand. Fires a one-shot agent job that calls generate_investigation_report
  // (which assembles the markdown from the verdict, blast radius, techniques,
  // indicators, and timeline, then stores it on the issue), then polls until
  // the issue's `report` field changes. Mirrors `regenerate` (diagrams).
  const generateReport = async () => {
    if (!issue || genReport) return;
    setGenReport(true);
    const before = issue.report ?? "";
    const message =
      `Generate the investigation report for Guardian Issue ${id}. ` +
      `First call issue_get(issue_id="${id}") to read the full investigation ` +
      `(summary, conclusions, verdict, blast radius, techniques, timeline). ` +
      `If a structured verdict is not set yet, decide one from the evidence and ` +
      `record it with issue_set_verdict; map any ATT&CK techniques you can ` +
      `justify with issue_add_technique. Then call ` +
      `generate_investigation_report(issue_id="${id}") to assemble and store the ` +
      `report. Do only this — do not change unrelated fields.`;
    try {
      const resp = await fetch("/api/agent/jobs", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          name: `gen-report-${id}-${before.length}`,
          cron: "* * * * *",
          timezone: "UTC",
          run_once: true,
          enabled: true,
          bypass_approvals: true,
          action: { type: "prompt", skill: "xsoar_case_investigation", message },
        }),
      });
      if (!resp.ok) {
        const detail = await resp.json().catch(() => ({}));
        throw new Error((detail as { error?: string })?.error ?? `report generation failed (${resp.status})`);
      }
      const deadline = Date.now() + 180_000;
      let updated = false;
      while (Date.now() < deadline) {
        await new Promise((r) => setTimeout(r, 5000));
        try {
          const det = await getIssue(id);
          if (det.report && det.report !== before) {
            setIssue(det);
            updated = true;
            break;
          }
        } catch {
          /* transient — keep polling */
        }
      }
      if (!updated) {
        try { setIssue(await getIssue(id)); } catch { /* ignore */ }
        setError("Report generation timed out — the agent run may have failed. Try again.");
      }
    } catch (e) {
      setError(e instanceof Error ? e.message : "report generation failed");
    } finally {
      setGenReport(false);
    }
  };

  const activityTypes = useMemo(
    () => Array.from(new Set((issue?.events ?? []).map((e) => e.type))),
    [issue],
  );
  const displayedEvents = useMemo(() => {
    const evs = (issue?.events ?? []).filter((e) => actType === "all" || e.type === actType);
    return [...evs].sort((a, b) =>
      actSort === "oldest" ? a.ts.localeCompare(b.ts) : b.ts.localeCompare(a.ts),
    );
  }, [issue, actType, actSort]);

  if (loading) return <p className="text-sm text-on-surface-variant p-8 text-center">Loading…</p>;
  if (error) return <p className="text-sm text-error p-8 text-center">{error}</p>;
  if (!issue) return <p className="text-sm text-on-surface-variant p-8 text-center">Issue not found.</p>;

  const { verdict: summaryVerdict } = splitVerdict(issue.summary);
  // v0.2.45 — prefer the structured verdict (set via issue_set_verdict) over the
  // legacy leading "VERDICT:" line in the summary; render the enum in Title Case
  // (verdictTone lowercases internally, so the tone mapping still resolves).
  const verdict = issue.verdict
    ? issue.verdict.replace(/_/g, " ").toLowerCase().replace(/\b\w/g, (c) => c.toUpperCase())
    : summaryVerdict;
  const layout = kindLayout(issue.kind);

  return (
    <div className="max-w-[1400px] mx-auto px-8 py-8 pb-32">
      <Link href="/investigation/issues" className="text-xs text-on-surface-variant hover:text-on-surface inline-flex items-center gap-1 mb-4">
        <span className="material-symbols-outlined text-[16px]">arrow_back</span> Issues
      </Link>

      {/* Header */}
      <div className="rounded-2xl p-6 mb-6" style={glassStyle}>
        <div className="flex items-start gap-4">
          <span className={`material-symbols-outlined text-2xl mt-0.5 ${layout.accent}`}>{layout.icon}</span>
          <div className="flex-1 min-w-0">
            <h1 className="font-headline text-2xl font-bold tracking-tight text-on-surface">{issue.title}</h1>
            <div className="flex flex-wrap items-center gap-2 mt-2">
              <Badge tone={STATUS_TOKENS[issue.status]}>{issue.status}</Badge>
              <Badge tone={SEVERITY_TOKENS[issue.severity]}>{issue.severity}</Badge>
              <Badge>{kindLabel(issue.kind)}</Badge>
              <OriginChip origin={issue.origin} />
              {issue.source_ref && (
                <span className="inline-flex items-center gap-0.5 text-[11px] text-on-surface-variant">
                  <span className="material-symbols-outlined text-[14px]">tag</span>XSOAR {issue.source_ref}
                </span>
              )}
              <span className="text-[11px] text-on-surface-variant/60">updated {fmtTs(issue.updated_at)}</span>
            </div>
            <p className="text-xs text-on-surface-variant/80 mt-2 flex items-start gap-1.5">
              <span className="material-symbols-outlined text-[14px] mt-0.5 shrink-0">center_focus_strong</span>
              <span>{layout.focus}</span>
            </p>
          </div>
        </div>

        {/* Verdict banner — structured verdict if set, else the summary's
            leading VERDICT: line. Confidence (when present) sits on the right. */}
        {verdict && (
          <div className={`mt-4 rounded-xl border px-4 py-2.5 flex items-center gap-2 ${verdictTone(verdict)}`}>
            <span className="material-symbols-outlined text-[18px]">gavel</span>
            <span className="text-sm font-medium">{verdict}</span>
            {issue.verdict_confidence != null && (
              <span className="ml-auto text-[11px] font-medium opacity-80">
                {Math.round(issue.verdict_confidence * 100)}% confidence
              </span>
            )}
          </div>
        )}

        {/* Control bar */}
        <div className="flex flex-wrap items-center gap-x-6 gap-y-3 mt-5 pt-5 border-t border-white/10">
          <Control label="Status">
            <select
              value={issue.status}
              onChange={(e) => patch({ status: e.target.value as IssueDetail["status"] })}
              className={`rounded-lg px-3 py-1.5 text-xs font-medium border bg-surface-container-high ${STATUS_TOKENS[issue.status] ?? ""}`}
            >
              {STATUSES.map((s) => <option key={s} value={s}>{s}</option>)}
            </select>
          </Control>
          <Control label="Severity">
            <select
              value={issue.severity}
              onChange={(e) => patch({ severity: e.target.value as IssueDetail["severity"] })}
              className={`rounded-lg px-3 py-1.5 text-xs font-medium border bg-surface-container-high ${SEVERITY_TOKENS[issue.severity] ?? ""}`}
            >
              {SEVERITIES.map((s) => <option key={s} value={s}>{s}</option>)}
            </select>
          </Control>
          <Control label="Case">
            <CaseAssigner issue={issue} cases={cases} onAssigned={load} />
          </Control>
          {/* Manual analyst actions live here (v0.1.7 placeholder — wired in a later release). */}
          <div className="ml-auto flex items-center gap-2 opacity-50">
            <button
              type="button"
              disabled
              title="Manual analyst actions — coming soon"
              className="inline-flex items-center gap-1.5 rounded-lg border border-outline-variant px-3 py-1.5 text-xs text-on-surface-variant cursor-not-allowed"
            >
              <span className="material-symbols-outlined text-[16px]">bolt</span>
              Actions
            </button>
          </div>
        </div>
      </div>

      {/* Tabs */}
      <InvestigationTabBar tabs={TABS} active={tab} onChange={setTab} />

      {tab === "overview" && (
        <div className="grid grid-cols-1 gap-4">
          <EditableSection icon="summarize" label="Summary" value={issue.summary ?? ""} onSave={(v) => patch({ summary: v })} />
          <EditableSection icon="center_focus_strong" label="Scope" value={issue.scope ?? ""} onSave={(v) => patch({ scope: v })} />
          <EditableSection icon="lightbulb" label="Recommendations" value={issue.recommendations ?? ""} onSave={(v) => patch({ recommendations: v })} />
        </div>
      )}

      {tab === "assessment" && (
        <div className="grid grid-cols-1 gap-4">
          <StructuredOutcome issue={issue} />
          <TechniqueChips techniques={issue.techniques} />
          <EditableSection icon="gavel" label="Conclusions" value={issue.conclusions ?? ""} onSave={(v) => patch({ conclusions: v })} />
          <EditableSection icon="checklist" label="Next steps" value={issue.next_steps ?? ""} onSave={(v) => patch({ next_steps: v })} />
        </div>
      )}

      {tab === "report" && (
        <div className="grid grid-cols-1 gap-3">
          <div className="flex justify-end">
            <a
              href={`/api/agent/issues/${id}/stix`}
              download={`guardian-issue-${id}-stix.json`}
              className="inline-flex items-center gap-1.5 rounded-lg border border-outline-variant px-3 py-1.5 text-[11px] text-on-surface-variant hover:text-on-surface"
            >
              <span className="material-symbols-outlined text-[14px]">download</span>
              Export STIX 2.1
            </a>
          </div>
          <ReportTab
            report={issue.report}
            busy={genReport}
            disabled={genReport}
            onGenerate={generateReport}
          />
        </div>
      )}

      {tab === "indicators" && (
        issueIndicators.length === 0 ? (
          <EmptyState
            icon="fingerprint"
            title="No indicators extracted yet"
            hint="As Guardian enriches IoCs during this investigation — or imports them from the fetched XSOAR case — they appear here (and on the Indicators page). Types that matter for this case kind are highlighted."
          />
        ) : (
          <div className="grid grid-cols-1 gap-3">
            {issueIndicators.map((ind) => (
              <IndicatorRow
                key={ind.id}
                indicator={ind}
                href={`/investigation/indicators/${ind.id}`}
                emphasized={layout.iocTypes.includes(ind.type)}
              />
            ))}
          </div>
        )
      )}

      {tab === "activity" && (
        <div>
          {issue.events.length === 0 ? (
            <EmptyState icon="timeline" title="No activity yet" hint="As Guardian investigates, each step and finding appears here as a timeline entry." />
          ) : (
            <>
              <div className="flex flex-wrap items-center gap-3 mb-4">
                <div className="flex items-center gap-1.5 rounded-2xl p-1.5" style={glassStyle}>
                  {["all", ...activityTypes].map((t) => (
                    <button
                      key={t}
                      onClick={() => setActType(t)}
                      className={`rounded-lg px-3 py-1.5 text-[11px] uppercase tracking-wider font-medium transition ${
                        actType === t
                          ? "bg-secondary-container/40 border border-secondary/40 text-secondary"
                          : "border border-transparent text-on-surface-variant hover:text-on-surface hover:bg-white/5"
                      }`}
                    >
                      {t}
                    </button>
                  ))}
                </div>
                <button
                  onClick={() => setActSort((s) => (s === "oldest" ? "newest" : "oldest"))}
                  className="inline-flex items-center gap-1 text-[11px] text-on-surface-variant hover:text-on-surface rounded-lg border border-outline-variant px-3 py-1.5"
                >
                  <span className="material-symbols-outlined text-[14px]">{actSort === "oldest" ? "arrow_downward" : "arrow_upward"}</span>
                  {actSort === "oldest" ? "Oldest first" : "Newest first"}
                </button>
                <span className="text-[11px] text-on-surface-variant/60 ml-auto">
                  {displayedEvents.length} of {issue.events.length}
                </span>
              </div>
              <ol className="space-y-3">
                {displayedEvents.map((ev) => (
                  <li key={ev.id} className="flex gap-3 rounded-2xl p-4" style={glassStyle}>
                    <span className="h-8 w-8 rounded-full bg-surface-container-highest border border-primary/40 flex items-center justify-center shrink-0 text-primary">
                      <span className="material-symbols-outlined text-[16px]">{EVENT_ICONS[ev.type] ?? "circle"}</span>
                    </span>
                    <div className="flex-1 min-w-0">
                      <div className="flex items-center gap-2 text-[11px] text-on-surface-variant">
                        <span className="font-bold uppercase tracking-wide">{ev.type}</span>
                        <span className="text-on-surface-variant/60">{fmtTs(ev.ts)}</span>
                      </div>
                      <div className="text-sm mt-1">
                        <MarkdownContent compact>{ev.content}</MarkdownContent>
                      </div>
                    </div>
                  </li>
                ))}
              </ol>
            </>
          )}
        </div>
      )}

      {tab === "chain" && (
        <DiagramTab
          svg={issue.attack_chain_svg}
          icon="account_tree"
          title="Attack chain"
          alt="Attack chain diagram"
          emptyHint="Guardian draws the causality / attack chain when it resolves an investigation. You can also generate it now (a full agent pass — takes about a minute)."
          busy={regenerating === "chain"}
          disabled={regenerating !== null}
          onRegenerate={() => regenerate("chain")}
        />
      )}

      {tab === "relations" && (
        <DiagramTab
          svg={issue.relations_canvas_svg}
          icon="hub"
          title="Relations canvas"
          alt="STIX relations canvas"
          emptyHint="A STIX graph of this issue's indicators and how they relate to each other and to ATT&CK techniques, malware, campaigns, and threat-actors. Generate it on demand — Guardian records the relationships (indicator_relate) and draws the canvas in one agent pass (about a minute)."
          busy={regenerating === "relations"}
          disabled={regenerating !== null}
          onRegenerate={() => regenerate("relations")}
        />
      )}
    </div>
  );
}


// DiagramTab now lives in components/investigation/ui.tsx (shared with the
// case detail page — v0.2.2).

function Control({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <div className="flex items-center gap-2">
      <label className="text-[10px] uppercase tracking-widest text-on-surface-variant">{label}</label>
      {children}
    </div>
  );
}

// ── Structured outcome (v0.2.45 — stage A) ─────────────────────────────
// Card shells mirror EditableSection's header (icon + label over a glass body)
// so the Assessment tab reads as one consistent column.
function OutcomeCard({ icon, label, children }: { icon: string; label: string; children: React.ReactNode }) {
  return (
    <div className="rounded-2xl p-5" style={glassStyle}>
      <div className="flex items-center gap-2 mb-3">
        <span className="material-symbols-outlined text-[18px] text-on-surface-variant">{icon}</span>
        <span className="text-[10px] uppercase tracking-widest text-on-surface-variant">{label}</span>
      </div>
      {children}
    </div>
  );
}

function humanizeKey(k: string): string {
  return k.replace(/[_-]+/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());
}

// Parse the JSON-encoded blast_radius into a plain object (or null if unset /
// malformed — the agent writes it via issue_set_verdict so it's normally valid).
function parseBlastRadius(raw: string | null): Record<string, unknown> | null {
  if (!raw) return null;
  try {
    const o = JSON.parse(raw);
    return o && typeof o === "object" && !Array.isArray(o) ? (o as Record<string, unknown>) : null;
  } catch {
    return null;
  }
}

function StructuredOutcome({ issue }: { issue: IssueDetail }) {
  const blast = parseBlastRadius(issue.blast_radius);
  const hasOutcome = issue.verdict != null || issue.verdict_confidence != null || blast != null;
  if (!hasOutcome) {
    return (
      <OutcomeCard icon="verified" label="Structured outcome">
        <p className="text-xs text-on-surface-variant/80">
          No structured verdict yet. Guardian records the verdict, a 0–100%
          confidence, and the blast radius (impacted hosts, accounts, data) via{" "}
          <code className="text-on-surface">issue_set_verdict</code> when it concludes
          the investigation.
        </p>
      </OutcomeCard>
    );
  }
  const pct = issue.verdict_confidence != null ? Math.round(issue.verdict_confidence * 100) : null;
  return (
    <OutcomeCard icon="verified" label="Structured outcome">
      {issue.verdict && (
        <div className="flex items-center gap-2 mb-3">
          <Badge tone={verdictTone(issue.verdict.replace(/_/g, " "))}>
            {humanizeKey(issue.verdict)}
          </Badge>
        </div>
      )}
      {pct != null && (
        <div className="mb-4">
          <div className="flex items-center justify-between text-[11px] text-on-surface-variant mb-1">
            <span>Confidence</span>
            <span className="font-medium text-on-surface">{pct}%</span>
          </div>
          <div className="h-1.5 w-full rounded-full bg-surface-container-highest overflow-hidden">
            <div className="h-full rounded-full bg-primary" style={{ width: `${pct}%` }} />
          </div>
        </div>
      )}
      {blast && Object.keys(blast).length > 0 && (
        <div>
          <div className="text-[11px] text-on-surface-variant mb-2">Blast radius</div>
          <dl className="grid grid-cols-1 gap-2">
            {Object.entries(blast).map(([k, v]) => (
              <div key={k} className="flex flex-wrap items-start gap-2">
                <dt className="text-[11px] uppercase tracking-wide text-on-surface-variant/70 min-w-[88px] pt-0.5">
                  {humanizeKey(k)}
                </dt>
                <dd className="flex flex-wrap gap-1.5">
                  {Array.isArray(v) ? (
                    v.length === 0 ? (
                      <span className="text-xs text-on-surface-variant/60">—</span>
                    ) : (
                      v.map((item, i) => (
                        <span key={i} className="rounded-md bg-surface-container-highest border border-outline-variant px-2 py-0.5 text-[11px] text-on-surface">
                          {String(item)}
                        </span>
                      ))
                    )
                  ) : (
                    <span className="text-xs text-on-surface">{String(v)}</span>
                  )}
                </dd>
              </div>
            ))}
          </dl>
        </div>
      )}
    </OutcomeCard>
  );
}

function TechniqueChips({ techniques }: { techniques: TechniqueMapping[] }) {
  return (
    <OutcomeCard icon="lan" label="ATT&CK techniques">
      {techniques.length === 0 ? (
        <p className="text-xs text-on-surface-variant/80">
          No techniques mapped yet. Guardian links observed ATT&CK techniques to
          this issue via <code className="text-on-surface">issue_add_technique</code>{" "}
          — they also power the cross-incident{" "}
          <Link href="/investigation/issues" className="text-secondary hover:underline">technique pivot</Link>.
        </p>
      ) : (
        <div className="flex flex-wrap gap-2">
          {techniques.map((t) => (
            <div
              key={t.id}
              title={[t.manifestation, t.evidence_ref].filter(Boolean).join(" · ") || undefined}
              className="inline-flex items-center gap-1.5 rounded-lg border border-tertiary/40 bg-tertiary/10 px-2.5 py-1 text-[11px] text-tertiary"
            >
              <span className="material-symbols-outlined text-[14px]">lan</span>
              <span className="font-mono font-medium">{t.technique_id}</span>
              {t.tactic && <span className="text-tertiary/70">· {t.tactic}</span>}
              {t.confidence != null && (
                <span className="text-tertiary/70">· {Math.round(t.confidence * 100)}%</span>
              )}
            </div>
          ))}
        </div>
      )}
    </OutcomeCard>
  );
}

function ReportTab({
  report,
  busy,
  disabled,
  onGenerate,
}: {
  report: string | null;
  busy: boolean;
  disabled: boolean;
  onGenerate: () => void;
}) {
  if (!report) {
    return (
      <div className="flex flex-col items-center gap-4">
        <EmptyState
          icon="description"
          title="No report generated yet"
          hint="Guardian assembles a structured closure report — verdict, blast radius, ATT&CK techniques, indicators, and the investigation timeline — into one markdown document. Generate it on demand (a full agent pass — about a minute)."
        />
        <button
          onClick={onGenerate}
          disabled={disabled}
          className="inline-flex items-center gap-2 rounded-xl border border-primary/40 bg-primary/10 px-4 py-2 text-sm font-medium text-primary hover:bg-primary/20 disabled:opacity-50 disabled:cursor-not-allowed"
        >
          <span className={`material-symbols-outlined text-[18px] ${busy ? "animate-spin" : ""}`}>
            {busy ? "progress_activity" : "auto_awesome"}
          </span>
          {busy ? "Generating…" : "Generate report"}
        </button>
      </div>
    );
  }
  return (
    <div className="grid grid-cols-1 gap-4">
      <div className="flex justify-end">
        <button
          onClick={onGenerate}
          disabled={disabled}
          className="inline-flex items-center gap-1.5 rounded-lg border border-outline-variant px-3 py-1.5 text-[11px] text-on-surface-variant hover:text-on-surface disabled:opacity-50 disabled:cursor-not-allowed"
        >
          <span className={`material-symbols-outlined text-[14px] ${busy ? "animate-spin" : ""}`}>
            {busy ? "progress_activity" : "refresh"}
          </span>
          {busy ? "Regenerating…" : "Regenerate"}
        </button>
      </div>
      <div className="rounded-2xl p-6" style={glassStyle}>
        <MarkdownContent>{report}</MarkdownContent>
      </div>
    </div>
  );
}

function CaseAssigner({ issue, cases, onAssigned }: { issue: IssueDetail; cases: CaseRow[]; onAssigned: () => void }) {
  const assign = async (caseId: string) => {
    if (!caseId) return;
    await addIssueToCase(caseId, issue.id);
    onAssigned();
  };
  return issue.case ? (
    <Link
      href={`/investigation/cases/${issue.case.id}`}
      className="inline-flex items-center gap-1 text-xs text-secondary hover:underline rounded-lg border border-secondary/40 bg-secondary-container/30 px-3 py-1.5"
    >
      <span className="material-symbols-outlined text-[14px]">folder</span>
      {issue.case.title}
    </Link>
  ) : (
    <select
      defaultValue=""
      onChange={(e) => assign(e.target.value)}
      className="rounded-lg px-3 py-1.5 text-xs border border-outline-variant text-on-surface-variant bg-surface-container-high"
    >
      <option value="">unassigned…</option>
      {cases.map((c) => <option key={c.id} value={c.id}>{c.title}</option>)}
    </select>
  );
}
