"use client";

import Link from "next/link";
import { useParams } from "next/navigation";
import { useCallback, useEffect, useMemo, useState } from "react";
import { MarkdownContent } from "@/components/markdown-content";
import {
  getIssue,
  updateIssue,
  listCases,
  listIndicators,
  addIssueToCase,
  kindLabel,
  SEVERITY_TOKENS,
  STATUS_TOKENS,
  type IssueDetail,
  type CaseRow,
  type Indicator,
} from "@/lib/api/investigation";
import {
  glassStyle,
  Badge,
  OriginChip,
  InvestigationTabBar,
  EditableSection,
  EmptyState,
  IndicatorRow,
  kindLayout,
  fmtTs,
  splitVerdict,
  verdictTone,
} from "@/components/investigation/ui";

/**
 * Investigation → Issue detail (v0.1.7 — full-width, tabbed layout).
 *
 * Header (title + verdict banner + status/severity/case controls) over a
 * tabbed body: Overview (summary · scope · recommendations), Assessment
 * (conclusions · next steps), Activity (the issue_events timeline), and
 * Attack chain (the SVG causality diagram — stubbed here, generated by the
 * diagramming skill in v0.1.8). Operator-editable fields are what the agent
 * fills via issue_update; the timeline is what it appended via issue_add_event.
 */

const STATUSES = ["open", "investigating", "resolved", "closed"];
const SEVERITIES = ["low", "medium", "high", "critical"];

type Tab = "overview" | "assessment" | "indicators" | "activity" | "chain" | "relations";
const TABS: { key: Tab; label: string; icon: string }[] = [
  { key: "overview", label: "Overview", icon: "dashboard" },
  { key: "assessment", label: "Assessment", icon: "gavel" },
  { key: "indicators", label: "Indicators", icon: "fingerprint" },
  { key: "activity", label: "Activity", icon: "timeline" },
  { key: "chain", label: "Attack chain", icon: "account_tree" },
  { key: "relations", label: "Relations", icon: "hub" },
];

const EVENT_ICONS: Record<string, string> = {
  action: "bolt",
  finding: "search_insights",
  note: "sticky_note_2",
  conversation: "forum",
};

export default function IssueDetailPage() {
  const params = useParams<{ id: string }>();
  const id = params.id;
  const [issue, setIssue] = useState<IssueDetail | null>(null);
  const [cases, setCases] = useState<CaseRow[]>([]);
  const [issueIndicators, setIssueIndicators] = useState<Indicator[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [tab, setTab] = useState<Tab>("overview");
  // null = idle; otherwise the diagram kind currently regenerating (only one at a time).
  const [regenerating, setRegenerating] = useState<null | "chain" | "relations">(null);
  const [actType, setActType] = useState("all");
  const [actSort, setActSort] = useState<"oldest" | "newest">("oldest");

  // `silent` skips the full-page spinner — used for patch-triggered refetches
  // so editing a field doesn't flash the loading state. The initial mount (and
  // inter-issue navigation, which reuses this component with a new id) loads
  // non-silently so we never show one issue's content under another's id.
  const load = useCallback(async (silent = false) => {
    if (!silent) setLoading(true);
    setError(null);
    try {
      const [det, cl, inds] = await Promise.all([
        getIssue(id),
        listCases(),
        listIndicators({ issue_id: id }),
      ]);
      setIssue(det);
      setCases(cl.cases);
      setIssueIndicators(inds.indicators);
    } catch (e) {
      setError(e instanceof Error ? e.message : "failed to load issue");
    } finally {
      setLoading(false);
    }
  }, [id]);

  useEffect(() => {
    load();
  }, [load]);

  const patch = async (body: Parameters<typeof updateIssue>[1]) => {
    if (!issue) return;
    try {
      await updateIssue(id, body);
      load(true);
    } catch (e) {
      setError(e instanceof Error ? e.message : "update failed");
    }
  };

  // Regenerate a diagram on demand: fire a one-shot agent job (reuses the
  // scheduler — the agent reads the issue and draws the SVG via the matching
  // skill, then stores it with the matching tool), then poll the issue until
  // the relevant SVG field changes. Heavy op (a full agent turn), so we poll
  // up to ~3 min and show a spinner. One code path drives both diagram kinds —
  // only the skill, the storage tool, and the watched field differ.
  const regenerate = async (kind: "chain" | "relations") => {
    if (!issue || regenerating) return;
    setRegenerating(kind);
    const isChain = kind === "chain";
    const before = (isChain ? issue.attack_chain_svg : issue.relations_canvas_svg) ?? "";
    const skill = isChain ? "svg_attack_chain" : "svg_relation_graph";
    const message = isChain
      ? `Regenerate the attack-chain diagram for Guardian Issue ${id}. ` +
        `First call issue_get(issue_id="${id}") to read the investigation ` +
        `(summary, conclusions, activity timeline). Then, per the ` +
        `svg_attack_chain skill, draw a self-contained SVG of the attack's ` +
        `causal path and store it with issue_set_attack_chain(issue_id="${id}", ` +
        `svg="<the full svg>"). Do only this — do not change any other field.`
      : `Regenerate the STIX relations canvas for Guardian Issue ${id}. ` +
        `First call indicators_list(issue_id="${id}"), then indicator_get(id) for ` +
        `each indicator to read its relationships. Where obvious edges are missing ` +
        `(domain resolves-to ip, indicator indicates malware / uses a technique / ` +
        `attributed-to an actor), record them first with indicator_relate. Then, ` +
        `per the svg_relation_graph skill, draw a self-contained layered SVG of the ` +
        `indicators and their STIX relationships and store it with ` +
        `issue_set_relation_graph(issue_id="${id}", svg="<the full svg>"). ` +
        `Do only this — do not change any other field.`;
    try {
      await fetch("/api/agent/jobs", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          name: `regen-${kind}-${id}`,
          cron: "* * * * *",
          timezone: "UTC",
          run_once: true,
          enabled: true,
          bypass_approvals: true,
          action: { type: "prompt", skill, message },
        }),
      });
      const deadline = Date.now() + 180_000;
      while (Date.now() < deadline) {
        await new Promise((r) => setTimeout(r, 5000));
        try {
          const det = await getIssue(id);
          const now = (isChain ? det.attack_chain_svg : det.relations_canvas_svg) ?? "";
          if (now && now !== before) {
            setIssue(det);
            break;
          }
        } catch {
          /* transient — keep polling */
        }
      }
    } catch (e) {
      setError(e instanceof Error ? e.message : "regenerate failed");
    } finally {
      setRegenerating(null);
    }
  };

  const activityTypes = useMemo(
    () => Array.from(new Set((issue?.events ?? []).map((e) => e.type))),
    [issue],
  );
  const displayedEvents = useMemo(() => {
    const evs = (issue?.events ?? []).filter((e) => actType === "all" || e.type === actType);
    return [...evs].sort((a, b) =>
      actSort === "oldest" ? a.ts.localeCompare(b.ts) : b.ts.localeCompare(a.ts),
    );
  }, [issue, actType, actSort]);

  if (loading) return <p className="text-sm text-on-surface-variant p-8 text-center">Loading…</p>;
  if (error) return <p className="text-sm text-error p-8 text-center">{error}</p>;
  if (!issue) return <p className="text-sm text-on-surface-variant p-8 text-center">Issue not found.</p>;

  const { verdict } = splitVerdict(issue.summary);
  const layout = kindLayout(issue.kind);

  return (
    <div className="max-w-[1400px] mx-auto px-8 py-8 pb-32">
      <Link href="/investigation/issues" className="text-xs text-on-surface-variant hover:text-on-surface inline-flex items-center gap-1 mb-4">
        <span className="material-symbols-outlined text-[16px]">arrow_back</span> Issues
      </Link>

      {/* Header */}
      <div className="rounded-2xl p-6 mb-6" style={glassStyle}>
        <div className="flex items-start gap-4">
          <span className={`material-symbols-outlined text-2xl mt-0.5 ${layout.accent}`}>{layout.icon}</span>
          <div className="flex-1 min-w-0">
            <h1 className="font-headline text-2xl font-bold tracking-tight text-on-surface">{issue.title}</h1>
            <div className="flex flex-wrap items-center gap-2 mt-2">
              <Badge tone={STATUS_TOKENS[issue.status]}>{issue.status}</Badge>
              <Badge tone={SEVERITY_TOKENS[issue.severity]}>{issue.severity}</Badge>
              <Badge>{kindLabel(issue.kind)}</Badge>
              <OriginChip origin={issue.origin} />
              {issue.source_ref && (
                <span className="inline-flex items-center gap-0.5 text-[11px] text-on-surface-variant">
                  <span className="material-symbols-outlined text-[14px]">tag</span>XSOAR {issue.source_ref}
                </span>
              )}
              <span className="text-[11px] text-on-surface-variant/60">updated {fmtTs(issue.updated_at)}</span>
            </div>
            <p className="text-xs text-on-surface-variant/80 mt-2 flex items-start gap-1.5">
              <span className="material-symbols-outlined text-[14px] mt-0.5 shrink-0">center_focus_strong</span>
              <span>{layout.focus}</span>
            </p>
          </div>
        </div>

        {/* Verdict banner (derived from the summary's leading VERDICT: line) */}
        {verdict && (
          <div className={`mt-4 rounded-xl border px-4 py-2.5 flex items-center gap-2 ${verdictTone(verdict)}`}>
            <span className="material-symbols-outlined text-[18px]">gavel</span>
            <span className="text-sm font-medium">{verdict}</span>
          </div>
        )}

        {/* Control bar */}
        <div className="flex flex-wrap items-center gap-x-6 gap-y-3 mt-5 pt-5 border-t border-white/10">
          <Control label="Status">
            <select
              value={issue.status}
              onChange={(e) => patch({ status: e.target.value as IssueDetail["status"] })}
              className={`rounded-lg px-3 py-1.5 text-xs font-medium border bg-surface-container-high ${STATUS_TOKENS[issue.status] ?? ""}`}
            >
              {STATUSES.map((s) => <option key={s} value={s}>{s}</option>)}
            </select>
          </Control>
          <Control label="Severity">
            <select
              value={issue.severity}
              onChange={(e) => patch({ severity: e.target.value as IssueDetail["severity"] })}
              className={`rounded-lg px-3 py-1.5 text-xs font-medium border bg-surface-container-high ${SEVERITY_TOKENS[issue.severity] ?? ""}`}
            >
              {SEVERITIES.map((s) => <option key={s} value={s}>{s}</option>)}
            </select>
          </Control>
          <Control label="Case">
            <CaseAssigner issue={issue} cases={cases} onAssigned={load} />
          </Control>
          {/* Manual analyst actions live here (v0.1.7 placeholder — wired in a later release). */}
          <div className="ml-auto flex items-center gap-2 opacity-50">
            <button
              type="button"
              disabled
              title="Manual analyst actions — coming soon"
              className="inline-flex items-center gap-1.5 rounded-lg border border-outline-variant px-3 py-1.5 text-xs text-on-surface-variant cursor-not-allowed"
            >
              <span className="material-symbols-outlined text-[16px]">bolt</span>
              Actions
            </button>
          </div>
        </div>
      </div>

      {/* Tabs */}
      <InvestigationTabBar tabs={TABS} active={tab} onChange={setTab} />

      {tab === "overview" && (
        <div className="grid grid-cols-1 gap-4">
          <EditableSection icon="summarize" label="Summary" value={issue.summary ?? ""} onSave={(v) => patch({ summary: v })} />
          <EditableSection icon="center_focus_strong" label="Scope" value={issue.scope ?? ""} onSave={(v) => patch({ scope: v })} />
          <EditableSection icon="lightbulb" label="Recommendations" value={issue.recommendations ?? ""} onSave={(v) => patch({ recommendations: v })} />
        </div>
      )}

      {tab === "assessment" && (
        <div className="grid grid-cols-1 gap-4">
          <EditableSection icon="gavel" label="Conclusions" value={issue.conclusions ?? ""} onSave={(v) => patch({ conclusions: v })} />
          <EditableSection icon="checklist" label="Next steps" value={issue.next_steps ?? ""} onSave={(v) => patch({ next_steps: v })} />
        </div>
      )}

      {tab === "indicators" && (
        issueIndicators.length === 0 ? (
          <EmptyState
            icon="fingerprint"
            title="No indicators extracted yet"
            hint="As Guardian enriches IoCs during this investigation — or imports them from the fetched XSOAR case — they appear here (and on the Indicators page). Types that matter for this case kind are highlighted."
          />
        ) : (
          <div className="grid grid-cols-1 gap-3">
            {issueIndicators.map((ind) => (
              <IndicatorRow
                key={ind.id}
                indicator={ind}
                href={`/investigation/indicators/${ind.id}`}
                emphasized={layout.iocTypes.includes(ind.type)}
              />
            ))}
          </div>
        )
      )}

      {tab === "activity" && (
        <div>
          {issue.events.length === 0 ? (
            <EmptyState icon="timeline" title="No activity yet" hint="As Guardian investigates, each step and finding appears here as a timeline entry." />
          ) : (
            <>
              <div className="flex flex-wrap items-center gap-3 mb-4">
                <div className="flex items-center gap-1.5 rounded-2xl p-1.5" style={glassStyle}>
                  {["all", ...activityTypes].map((t) => (
                    <button
                      key={t}
                      onClick={() => setActType(t)}
                      className={`rounded-lg px-3 py-1.5 text-[11px] uppercase tracking-wider font-medium transition ${
                        actType === t
                          ? "bg-secondary-container/40 border border-secondary/40 text-secondary"
                          : "border border-transparent text-on-surface-variant hover:text-on-surface hover:bg-white/5"
                      }`}
                    >
                      {t}
                    </button>
                  ))}
                </div>
                <button
                  onClick={() => setActSort((s) => (s === "oldest" ? "newest" : "oldest"))}
                  className="inline-flex items-center gap-1 text-[11px] text-on-surface-variant hover:text-on-surface rounded-lg border border-outline-variant px-3 py-1.5"
                >
                  <span className="material-symbols-outlined text-[14px]">{actSort === "oldest" ? "arrow_downward" : "arrow_upward"}</span>
                  {actSort === "oldest" ? "Oldest first" : "Newest first"}
                </button>
                <span className="text-[11px] text-on-surface-variant/60 ml-auto">
                  {displayedEvents.length} of {issue.events.length}
                </span>
              </div>
              <ol className="space-y-3">
                {displayedEvents.map((ev) => (
                  <li key={ev.id} className="flex gap-3 rounded-2xl p-4" style={glassStyle}>
                    <span className="h-8 w-8 rounded-full bg-surface-container-highest border border-primary/40 flex items-center justify-center shrink-0 text-primary">
                      <span className="material-symbols-outlined text-[16px]">{EVENT_ICONS[ev.type] ?? "circle"}</span>
                    </span>
                    <div className="flex-1 min-w-0">
                      <div className="flex items-center gap-2 text-[11px] text-on-surface-variant">
                        <span className="font-bold uppercase tracking-wide">{ev.type}</span>
                        <span className="text-on-surface-variant/60">{fmtTs(ev.ts)}</span>
                      </div>
                      <div className="text-sm mt-1">
                        <MarkdownContent compact>{ev.content}</MarkdownContent>
                      </div>
                    </div>
                  </li>
                ))}
              </ol>
            </>
          )}
        </div>
      )}

      {tab === "chain" && (
        <DiagramTab
          svg={issue.attack_chain_svg}
          icon="account_tree"
          title="Attack chain"
          alt="Attack chain diagram"
          emptyHint="Guardian draws the causality / attack chain when it resolves an investigation. You can also generate it now (a full agent pass — takes about a minute)."
          busy={regenerating === "chain"}
          disabled={regenerating !== null}
          onRegenerate={() => regenerate("chain")}
        />
      )}

      {tab === "relations" && (
        <DiagramTab
          svg={issue.relations_canvas_svg}
          icon="hub"
          title="Relations canvas"
          alt="STIX relations canvas"
          emptyHint="A STIX graph of this issue's indicators and how they relate to each other and to ATT&CK techniques, malware, campaigns, and threat-actors. Generate it on demand — Guardian records the relationships (indicator_relate) and draws the canvas in one agent pass (about a minute)."
          busy={regenerating === "relations"}
          disabled={regenerating !== null}
          onRegenerate={() => regenerate("relations")}
        />
      )}
    </div>
  );
}

/**
 * A diagram tab body — renders an agent-produced SVG sandboxed as an <img>
 * data-URI (SVG-in-img never executes script, so the markup can't run code),
 * or an empty state with a Generate button. Shared by the Attack-chain and
 * Relations tabs; the parent owns the regenerate job + polling.
 */
function DiagramTab({
  svg, icon, title, alt, emptyHint, busy, disabled, onRegenerate,
}: {
  svg: string | null;
  icon: string;
  title: string;
  alt: string;
  emptyHint: string;
  busy: boolean;
  disabled: boolean;
  onRegenerate: () => void;
}) {
  return svg ? (
    <div className="rounded-2xl p-5" style={glassStyle}>
      <div className="flex items-center justify-between mb-3">
        <h3 className="text-xs font-bold uppercase tracking-widest text-on-surface flex items-center gap-2">
          <span className="material-symbols-outlined text-[18px] text-on-surface-variant">{icon}</span>
          {title}
        </h3>
        <button
          onClick={onRegenerate}
          disabled={disabled}
          className="inline-flex items-center gap-1 text-[11px] text-primary hover:underline disabled:opacity-50"
        >
          <span className="material-symbols-outlined text-[14px]">{busy ? "hourglass_top" : "refresh"}</span>
          {busy ? "Regenerating… (≈1 min)" : "Regenerate"}
        </button>
      </div>
      <div className="rounded-xl overflow-hidden bg-surface-container-lowest border border-outline-variant">
        {/* eslint-disable-next-line @next/next/no-img-element */}
        <img
          src={`data:image/svg+xml;utf8,${encodeURIComponent(svg)}`}
          alt={alt}
          className="w-full h-auto block"
        />
      </div>
    </div>
  ) : (
    <EmptyState icon={icon} title={`No ${title.toLowerCase()} yet`} hint={emptyHint}>
      <button
        onClick={onRegenerate}
        disabled={disabled}
        className="mt-3 inline-flex items-center gap-1.5 rounded-xl bg-primary text-on-primary px-4 py-2 text-sm font-medium hover:opacity-90 transition disabled:opacity-50"
      >
        <span className="material-symbols-outlined text-[18px]">{busy ? "hourglass_top" : "auto_awesome"}</span>
        {busy ? "Generating… (≈1 min)" : "Generate diagram"}
      </button>
    </EmptyState>
  );
}

function Control({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <div className="flex items-center gap-2">
      <label className="text-[10px] uppercase tracking-widest text-on-surface-variant">{label}</label>
      {children}
    </div>
  );
}

function CaseAssigner({ issue, cases, onAssigned }: { issue: IssueDetail; cases: CaseRow[]; onAssigned: () => void }) {
  const assign = async (caseId: string) => {
    if (!caseId) return;
    await addIssueToCase(caseId, issue.id);
    onAssigned();
  };
  return issue.case ? (
    <Link
      href={`/investigation/cases/${issue.case.id}`}
      className="inline-flex items-center gap-1 text-xs text-secondary hover:underline rounded-lg border border-secondary/40 bg-secondary-container/30 px-3 py-1.5"
    >
      <span className="material-symbols-outlined text-[14px]">folder</span>
      {issue.case.title}
    </Link>
  ) : (
    <select
      defaultValue=""
      onChange={(e) => assign(e.target.value)}
      className="rounded-lg px-3 py-1.5 text-xs border border-outline-variant text-on-surface-variant bg-surface-container-high"
    >
      <option value="">unassigned…</option>
      {cases.map((c) => <option key={c.id} value={c.id}>{c.title}</option>)}
    </select>
  );
}
