#!/usr/bin/env bash
# Phantom — full Phase 5-11a smoke test.
#
# Walks every capability introduced in the v1.2-conformance refactor and
# reports PASS/FAIL for each check. Designed to run ON THE PHANTOM VM
# HOST. It hits the embedded MCP at localhost:8080 and the Next.js
# agent UI at localhost:3000 (both host ports docker-compose maps).
# In-container filesystem checks reach into phantom_agent via
# `docker compose exec` — that container ships both the Next.js UI
# and the embedded MCP per the v1.2 bundle design (no separate
# phantom-mcp container).
#
# Usage (on the phantom VM):
#   cd $VM_REMOTE_REPO
#   MCP_TOKEN=<token> ./bundles/spark/mcp/scripts/smoke_test.sh
#
# Optional env:
#   MCP_BASE="https://localhost:8080"  (default; flip to http:// for non-TLS)
#   AGENT_BASE="https://localhost:3000" (default; flip to http:// for non-TLS)
#   COMPOSE_DIR=/path/to/repo           (default: \$PWD; must contain docker-compose.yml)
#   VERBOSE=1                           print every response payload
#
# Exit code: 0 on all-pass, 1 if any check failed, 2 on bad invocation.
#
# TLS: as of v1.2 stage-3F, the stack is HTTPS-by-default with a self-
# signed cert auto-generated by the agent's entrypoint at first boot.
# This script's curl calls all pass -k (skip cert verify) so they accept
# the self-signed material. If you've configured a CA-signed cert and
# want strict verification, drop -k via the CURL_K env override.

set -uo pipefail

MCP_BASE="${MCP_BASE:-https://localhost:8080}"
AGENT_BASE="${AGENT_BASE:-https://localhost:3000}"
MCP_TOKEN="${MCP_TOKEN:-}"
VERBOSE="${VERBOSE:-0}"
COMPOSE_DIR="${COMPOSE_DIR:-$PWD}"
# -k accepts self-signed certs (the default for TLS-by-default mode).
# Override with CURL_K="" if you've installed a real CA cert and want
# strict verification.
CURL_K="${CURL_K:--k}"

if [[ -z "$MCP_TOKEN" ]]; then
  echo "ERROR: MCP_TOKEN not set in env."
  exit 2
fi

if ! command -v curl >/dev/null 2>&1; then
  echo "ERROR: curl not found. This script must run on the VM host, not"
  echo "       inside a container."
  exit 2
fi

# Filesystem checks reach into phantom_agent (which now hosts the
# embedded MCP — no separate phantom-mcp container exists).
DOCKER_EXEC=""
if command -v docker >/dev/null 2>&1 && [[ -f "$COMPOSE_DIR/docker-compose.yml" ]]; then
  DOCKER_EXEC="docker compose -f $COMPOSE_DIR/docker-compose.yml exec -T phantom-agent"
fi

PASSED=0
FAILED=0
SKIPPED=0
declare -a FAILURES=()

# ─── Output helpers ──────────────────────────────────────────────

C_PASS='\033[0;32m'
C_FAIL='\033[0;31m'
C_WARN='\033[0;33m'
C_BOLD='\033[1m'
C_DIM='\033[2m'
C_RESET='\033[0m'

section() {
  printf "\n${C_BOLD}━━━ %s ━━━${C_RESET}\n" "$1"
}

pass() {
  PASSED=$((PASSED + 1))
  printf "  ${C_PASS}✓${C_RESET} %s\n" "$1"
}

fail() {
  FAILED=$((FAILED + 1))
  FAILURES+=("$1")
  printf "  ${C_FAIL}✗${C_RESET} %s\n" "$1"
  if [[ -n "${2:-}" ]]; then
    printf "    ${C_DIM}%s${C_RESET}\n" "$2"
  fi
}

skip() {
  SKIPPED=$((SKIPPED + 1))
  printf "  ${C_WARN}~${C_RESET} %s ${C_DIM}(skipped: %s)${C_RESET}\n" "$1" "${2:-no reason}"
}

verbose() {
  if [[ "$VERBOSE" == "1" ]]; then
    printf "    ${C_DIM}%s${C_RESET}\n" "$1"
  fi
}

# ─── HTTP helpers ────────────────────────────────────────────────

# mcp_curl <method> <path> [body]
# Returns "STATUS:BODY" with status code prefixed.
mcp_curl() {
  local method="$1"
  local path="$2"
  local body="${3:-}"
  local args=(-s -w '\nHTTPSTATUS:%{http_code}' -X "$method" -H "Authorization: Bearer $MCP_TOKEN")
  if [[ -n "$CURL_K" ]]; then
    args+=("$CURL_K")
  fi
  if [[ -n "$body" ]]; then
    args+=(-H "Content-Type: application/json" -d "$body")
  fi
  local response
  response=$(curl "${args[@]}" "${MCP_BASE}${path}" 2>&1)
  local http_status
  http_status=$(echo "$response" | tail -n1 | sed 's/HTTPSTATUS://')
  local response_body
  response_body=$(echo "$response" | sed -e '$d')
  echo "${http_status}:${response_body}"
}

agent_curl() {
  local path="$1"
  local response
  response=$(curl $CURL_K -s -w '\nHTTPSTATUS:%{http_code}' "${AGENT_BASE}${path}" 2>&1)
  local http_status
  http_status=$(echo "$response" | tail -n1 | sed 's/HTTPSTATUS://')
  local response_body
  response_body=$(echo "$response" | sed -e '$d')
  echo "${http_status}:${response_body}"
}

# expect_json_field <STATUS:BODY> <jq-filter> <expected-value>
# Returns 0 if the JSON body's filter result equals expected.
expect_json_field() {
  local response="$1"
  local filter="$2"
  local expected="$3"
  local body="${response#*:}"
  local actual
  actual=$(echo "$body" | python3 -c "import sys, json; d = json.load(sys.stdin); $filter" 2>/dev/null)
  if [[ "$actual" == "$expected" ]]; then
    return 0
  else
    echo "   expected: $expected"
    echo "   actual:   $actual"
    return 1
  fi
}

# ─── Banner ──────────────────────────────────────────────────────

cat <<EOF
${C_BOLD}Phantom v1.2 Smoke Test${C_RESET}
  MCP base   : $MCP_BASE
  Agent base : $AGENT_BASE
  Token      : ${MCP_TOKEN:0:8}…
EOF

# ────────────────────────────────────────────────────────────────
# Phase 5 — Secrets capability
# ────────────────────────────────────────────────────────────────

section "Phase 5 — Secrets capability"

# T5.1 — secrets directory exists with mode 0700 (in-container check)
if [[ -n "$DOCKER_EXEC" ]]; then
  SECRET_DIR_MODE=$($DOCKER_EXEC ls -ld /app/data/secrets 2>/dev/null | awk '{print $1}' || echo "")
  if [[ "$SECRET_DIR_MODE" == "drwx------" ]]; then
    pass "T5.1 /app/data/secrets exists with mode 0700"
  else
    fail "T5.1 /app/data/secrets mode" "got: $SECRET_DIR_MODE"
  fi

  # T5.2 — at least one secret file exists with mode 0600
  SECRET_FILE_COUNT=$($DOCKER_EXEC find /app/data/secrets -type f 2>/dev/null | wc -l | tr -d ' ')
  if [[ "$SECRET_FILE_COUNT" -gt 0 ]]; then
    BAD_PERMS=$($DOCKER_EXEC find /app/data/secrets -type f ! -perm 600 2>/dev/null | wc -l | tr -d ' ')
    if [[ "$BAD_PERMS" -eq 0 ]]; then
      pass "T5.2 all $SECRET_FILE_COUNT secret file(s) have mode 0600"
    else
      fail "T5.2 secret file perms" "$BAD_PERMS file(s) not mode 0600"
    fi
  else
    skip "T5.2 secret file perms" "no secrets configured yet"
  fi
else
  skip "T5.1-2 secret-store filesystem checks" "docker compose not reachable from CWD"
fi

# T5.3 — instance secrets are stored as paths, not values
INST_RESP=$(mcp_curl GET "/api/v1/instances")
INST_STATUS="${INST_RESP%%:*}"
if [[ "$INST_STATUS" == "200" ]]; then
  HAS_REDACTION=$(echo "${INST_RESP#*:}" | python3 -c "
import sys, json
d = json.load(sys.stdin)
for inst in d.get('instances', []):
    for v in (inst.get('secrets') or {}).values():
        if v == '***':
            print('yes'); sys.exit(0)
print('no')
" 2>/dev/null)
  if [[ "$HAS_REDACTION" == "yes" ]]; then
    pass "T5.3 instance secrets returned as '***' (redacted) over the API"
  elif [[ "$HAS_REDACTION" == "no" ]]; then
    skip "T5.3 instance secret redaction" "no instances with secrets configured"
  else
    fail "T5.3 instance secret redaction" "unexpected response shape"
  fi
else
  fail "T5.3 GET /api/v1/instances" "HTTP $INST_STATUS"
fi

# ────────────────────────────────────────────────────────────────
# Phase 6 — Audit trail
# ────────────────────────────────────────────────────────────────

section "Phase 6 — Audit trail"

AUDIT_SUMMARY=$(mcp_curl GET "/api/v1/audit/summary")
AUDIT_STATUS="${AUDIT_SUMMARY%%:*}"
if [[ "$AUDIT_STATUS" == "200" ]]; then
  pass "T6.1 GET /api/v1/audit/summary returns 200"
  AUDIT_TOTAL=$(echo "${AUDIT_SUMMARY#*:}" | python3 -c "import sys,json; print(json.load(sys.stdin)['total'])" 2>/dev/null)
  if [[ -n "$AUDIT_TOTAL" && "$AUDIT_TOTAL" -gt 0 ]]; then
    pass "T6.2 audit log contains $AUDIT_TOTAL events"
  else
    fail "T6.2 audit log content" "no events found"
  fi
else
  fail "T6.1 audit summary endpoint" "HTTP $AUDIT_STATUS"
fi

# T6.3 — filter by action returns only that action
TOOL_CALLS=$(mcp_curl GET "/api/v1/audit?action=tool_call&limit=5")
ALL_TOOL_CALLS=$(echo "${TOOL_CALLS#*:}" | python3 -c "
import sys, json
d = json.load(sys.stdin)
events = d.get('events', [])
if not events:
    print('empty'); sys.exit(0)
print('ok' if all(e.get('action') == 'tool_call' for e in events) else 'mixed')
" 2>/dev/null)
case "$ALL_TOOL_CALLS" in
  ok) pass "T6.3 action filter (action=tool_call) returns only matching events" ;;
  empty) skip "T6.3 action filter" "no tool_call events yet" ;;
  *) fail "T6.3 action filter" "filter is leaky: returned non-tool_call events" ;;
esac

# T6.4 — actor attribution: should see at least one user:operator event
HAS_USER_ACTOR=$(mcp_curl GET "/api/v1/audit?actor=user:operator&limit=1" | python3 -c "
import sys, json
body = sys.stdin.read().split(':', 1)[1]
d = json.loads(body)
print('yes' if d.get('count', 0) > 0 else 'no')
" 2>/dev/null)
if [[ "$HAS_USER_ACTOR" == "yes" ]]; then
  pass "T6.4 user:operator actor attribution captured (admin endpoint hits)"
else
  skip "T6.4 user:operator actor" "no admin endpoint activity yet"
fi

# ────────────────────────────────────────────────────────────────
# Phase 7 — Approvals
# ────────────────────────────────────────────────────────────────

section "Phase 7 — Approvals"

APPROVALS_RESP=$(mcp_curl GET "/api/v1/approvals?limit=5")
APPROVALS_STATUS="${APPROVALS_RESP%%:*}"
if [[ "$APPROVALS_STATUS" == "200" ]]; then
  pass "T7.1 GET /api/v1/approvals returns 200"
else
  fail "T7.1 approvals endpoint" "HTTP $APPROVALS_STATUS"
fi

# T7.2 — invalid status filter returns 400
BAD_STATUS_RESP=$(mcp_curl GET "/api/v1/approvals?status=garbage")
BAD_STATUS_CODE="${BAD_STATUS_RESP%%:*}"
if [[ "$BAD_STATUS_CODE" == "400" ]]; then
  pass "T7.2 bad status filter returns 400 with allowed list"
else
  fail "T7.2 bad status filter" "HTTP $BAD_STATUS_CODE (expected 400)"
fi

# T7.3 — 404 on unknown approval id
UNKNOWN_RESP=$(mcp_curl POST "/api/v1/approvals/00000000-0000-0000-0000-000000000000/resolve" '{"decision":"approved"}')
UNKNOWN_CODE="${UNKNOWN_RESP%%:*}"
if [[ "$UNKNOWN_CODE" == "404" ]]; then
  pass "T7.3 resolve unknown id returns 404"
else
  fail "T7.3 resolve unknown id" "HTTP $UNKNOWN_CODE (expected 404)"
fi

# ────────────────────────────────────────────────────────────────
# Phase 8 — Sessions + Memory + Context
# ────────────────────────────────────────────────────────────────

section "Phase 8 — Sessions + Memory + Context"

# T8.1 — create a smoke-test session
SESSION_CREATE=$(mcp_curl POST "/api/v1/sessions" '{"title":"smoke-test","meta":{"smoke":true}}')
SESSION_CODE="${SESSION_CREATE%%:*}"
SESSION_ID=""
if [[ "$SESSION_CODE" == "201" ]]; then
  SESSION_ID=$(echo "${SESSION_CREATE#*:}" | python3 -c "import sys,json; print(json.load(sys.stdin)['session']['id'])" 2>/dev/null)
  if [[ -n "$SESSION_ID" ]]; then
    pass "T8.1 created session $SESSION_ID"
  else
    fail "T8.1 session create response shape" "${SESSION_CREATE#*:}"
  fi
else
  fail "T8.1 session create" "HTTP $SESSION_CODE"
fi

# T8.2 — append a message
if [[ -n "$SESSION_ID" ]]; then
  MSG_RESP=$(mcp_curl POST "/api/v1/sessions/${SESSION_ID}/messages" '{"role":"user","content":"smoke test ping"}')
  MSG_CODE="${MSG_RESP%%:*}"
  if [[ "$MSG_CODE" == "201" ]]; then
    pass "T8.2 message append returned 201"
  else
    fail "T8.2 message append" "HTTP $MSG_CODE"
  fi

  # Read it back
  HIST=$(mcp_curl GET "/api/v1/sessions/${SESSION_ID}/messages")
  HIST_CONTENT=$(echo "${HIST#*:}" | python3 -c "
import sys, json
d = json.load(sys.stdin)
msgs = d.get('messages', [])
print(msgs[0]['content'] if msgs else '')
" 2>/dev/null)
  if [[ "$HIST_CONTENT" == "smoke test ping" ]]; then
    pass "T8.3 message read-back matches what we wrote"
  else
    fail "T8.3 message read-back" "got: $HIST_CONTENT"
  fi
fi

# T8.4 — store and search memory
MEM_STORE=$(mcp_curl POST "/api/v1/memories" '{"key":"smoke-test-host","value":"The smoke-test host 192.0.2.1 is the canary for verification runs","scope":"agent"}')
MEM_CODE="${MEM_STORE%%:*}"
if [[ "$MEM_CODE" == "201" ]]; then
  pass "T8.4 memory store returned 201"

  MEM_SEARCH=$(mcp_curl POST "/api/v1/memories/search" '{"query":"canary verification host","limit":3}')
  HAS_HIT=$(echo "${MEM_SEARCH#*:}" | python3 -c "
import sys, json
d = json.load(sys.stdin)
hits = d.get('results', [])
print('yes' if any(h.get('key') == 'smoke-test-host' for h in hits) else 'no')
" 2>/dev/null)
  if [[ "$HAS_HIT" == "yes" ]]; then
    pass "T8.5 semantic search found smoke-test-host"
  else
    fail "T8.5 semantic search" "smoke-test-host not in top results"
  fi
else
  fail "T8.4 memory store" "HTTP $MEM_CODE"
fi

# T8.6 — context assembler
CTX=$(mcp_curl POST "/api/v1/context" '{"query":"summarize the canary host"}')
CTX_HAS_KNOWLEDGE=$(echo "${CTX#*:}" | python3 -c "
import sys, json
d = json.load(sys.stdin)
ctx = d.get('context', {})
out = []
if ctx.get('memories'): out.append('memories')
if ctx.get('knowledge'): out.append('knowledge')
if ctx.get('messages'): out.append('messages')
print(','.join(out) if out else 'empty')
" 2>/dev/null)
if [[ "$CTX_HAS_KNOWLEDGE" == *"memories"* || "$CTX_HAS_KNOWLEDGE" == *"knowledge"* ]]; then
  pass "T8.6 context assembled with sources: $CTX_HAS_KNOWLEDGE"
else
  fail "T8.6 context assembly" "no sources returned: $CTX_HAS_KNOWLEDGE"
fi

# ────────────────────────────────────────────────────────────────
# Phase 9 — Jobs scheduler
# ────────────────────────────────────────────────────────────────

section "Phase 9 — Jobs scheduler"

JOBS=$(mcp_curl GET "/api/v1/jobs")
JOB_NAMES=$(echo "${JOBS#*:}" | python3 -c "
import sys, json
d = json.load(sys.stdin)
print(','.join(j['name'] for j in d.get('jobs', [])))
" 2>/dev/null)
if [[ -n "$JOB_NAMES" ]]; then
  pass "T9.1 GET /api/v1/jobs lists: $JOB_NAMES"
else
  fail "T9.1 jobs list" "no jobs registered"
fi

# T9.2 — manual trigger
# URL-encode FIRST_JOB before splicing it into the path: operators can
# create jobs via /jobs/new with names containing spaces or unicode
# (the backend's only constraint is "no slashes / dots" for filesystem
# safety — see CroniterJobScheduler._job_yaml_path). With raw splicing
# a name like "Say hi back" hits the route as `Say hi back/run`, which
# curl mangles and the FastMCP matcher can't reverse — both T9.2 and
# T9.3 then read empty status from a 4xx body.
#
# v0.3.23: prefer a MANIFEST-declared job over operator-created runtime
# jobs. Runtime jobs (created via the chat agent or operator-edited
# YAML) often depend on the Vertex provider via chat-style action
# types — if Vertex is degraded for any reason (KEK mismatch, etc.),
# those jobs return status=failed and break the smoke. Manifest jobs
# are bundle-declared and stable across deployments; they're the
# deterministic choice for a smoke probe.
FIRST_JOB=$(echo "${JOBS#*:}" | python3 -c "
import sys, json
d = json.load(sys.stdin)
jobs = d.get('jobs', [])
# Prefer manifest-source jobs (deterministic, stable). Fall back to
# the first job overall if no manifest jobs exist (pre-bundle test
# harness, theoretical edge case).
manifest = [j for j in jobs if j.get('source') == 'manifest']
pick = manifest[0] if manifest else (jobs[0] if jobs else None)
print(pick['name'] if pick else '')
" 2>/dev/null)
if [[ -n "$FIRST_JOB" ]]; then
  FIRST_JOB_ENC=$(python3 -c "import sys, urllib.parse as u; print(u.quote(sys.argv[1], safe=''))" "$FIRST_JOB")
  RUN_RESP=$(mcp_curl POST "/api/v1/jobs/${FIRST_JOB_ENC}/run" "")
  RUN_STATUS=$(echo "${RUN_RESP#*:}" | python3 -c "
import sys, json
d = json.load(sys.stdin)
print(d.get('run', {}).get('status', ''))
" 2>/dev/null)
  if [[ "$RUN_STATUS" == "success" || "$RUN_STATUS" == "skipped" ]]; then
    pass "T9.2 manual trigger of $FIRST_JOB returned status=$RUN_STATUS"
  else
    # v0.3.23: include the picked job name in the failure message so
    # future debugging starts with "what job did the smoke pick?" —
    # the previous failure message just showed status=failed which
    # offered zero signal about which job dispatched.
    fail "T9.2 manual trigger of '$FIRST_JOB'" "status=$RUN_STATUS"
  fi

  # T9.3 — disable + re-enable round trip
  DIS=$(mcp_curl POST "/api/v1/jobs/${FIRST_JOB_ENC}/disable" "")
  DIS_ENABLED=$(echo "${DIS#*:}" | python3 -c "import sys,json; print(json.load(sys.stdin)['job']['enabled'])" 2>/dev/null)
  EN=$(mcp_curl POST "/api/v1/jobs/${FIRST_JOB_ENC}/enable" "")
  EN_ENABLED=$(echo "${EN#*:}" | python3 -c "import sys,json; print(json.load(sys.stdin)['job']['enabled'])" 2>/dev/null)
  if [[ "$DIS_ENABLED" == "False" && "$EN_ENABLED" == "True" ]]; then
    pass "T9.3 disable→enable round-trip ($DIS_ENABLED → $EN_ENABLED)"
  else
    fail "T9.3 disable/enable" "disable=$DIS_ENABLED, enable=$EN_ENABLED"
  fi
fi

# ────────────────────────────────────────────────────────────────
# Phase 10 — Knowledge base
# ────────────────────────────────────────────────────────────────

section "Phase 10 — Knowledge base"

KBS=$(mcp_curl GET "/api/v1/kbs")
KB_NAMES=$(echo "${KBS#*:}" | python3 -c "
import sys, json
d = json.load(sys.stdin)
for k in d.get('kbs', []):
    print(f'{k[\"name\"]}:{k[\"doc_count\"]}')
" 2>/dev/null)
if [[ -n "$KB_NAMES" ]]; then
  pass "T10.1 KBs loaded: $(echo "$KB_NAMES" | tr '\n' ' ')"
else
  fail "T10.1 KB list" "no KBs loaded"
fi

# T10.2 — fetch a specific doc by frontmatter id
PHANTOM_DOC=$(mcp_curl GET "/api/v1/kbs/phantom-soc/docs/PH-SOC-001")
DOC_TITLE=$(echo "${PHANTOM_DOC#*:}" | python3 -c "
import sys, json
d = json.load(sys.stdin)
print(d.get('document', {}).get('title', ''))
" 2>/dev/null)
if [[ -n "$DOC_TITLE" ]]; then
  pass "T10.2 GET /kbs/phantom-soc/docs/PH-SOC-001: '$DOC_TITLE'"
else
  fail "T10.2 doc fetch" "PH-SOC-001 not retrievable"
fi

# T10.3 — KB-scoped semantic search
KB_SEARCH=$(mcp_curl POST "/api/v1/kbs/phantom-soc/search" '{"query":"detection validation XSIAM","limit":1}')
TOP_DOC=$(echo "${KB_SEARCH#*:}" | python3 -c "
import sys, json
d = json.load(sys.stdin)
results = d.get('results', [])
print(results[0].get('doc_id', '') if results else '')
" 2>/dev/null)
if [[ -n "$TOP_DOC" ]]; then
  pass "T10.3 KB search top result: $TOP_DOC"
else
  fail "T10.3 KB search" "no results"
fi

# ────────────────────────────────────────────────────────────────
# Phase 11 — Next.js shell (agent UI)
# ────────────────────────────────────────────────────────────────
#
# Replaces the deprecated Phase 11a A2UI rendering checks (manifest,
# catalog, surface JSONL replay, /a2ui/<surface> markers). The agent
# UI is now a normal Next.js app — verify the pages it ships actually
# return 200 and the route table reflects what the sidebar links to.
# A2UI infrastructure was removed wholesale; the equivalent endpoints
# (/api/v1/ui/manifest, /api/v1/ui/catalogs/*, /api/v1/ui/surfaces/*)
# were also deleted, so no need to assert their absence.

section "Phase 11 — Next.js shell"

# T11.1 — root chat page returns 2xx and renders the sidebar
HOME_HTML=$(curl $CURL_K -sw '\n%{http_code}' "${AGENT_BASE}/" 2>&1)
HOME_CODE=$(echo "$HOME_HTML" | tail -n1)
HOME_BODY=$(echo "$HOME_HTML" | sed '$d')
if [[ "$HOME_CODE" =~ ^2[0-9][0-9]$ ]] && \
   echo "$HOME_BODY" | grep -q "Phantom Agent"; then
  pass "T11.1 / renders shell + chat (HTTP $HOME_CODE)"
else
  fail "T11.1 / chat page" "HTTP $HOME_CODE, body lacks 'Phantom Agent'"
fi

# T11.2 — admin pages return 2xx (the routes the new grouped sidebar
# links to). Skips routes that legitimately 401 without auth — we only
# care that they exist in the route table and don't 404.
#
# NOTE: /sessions was removed in PR #11 (jobs CRUD + chat persistence)
# because the chat-page sidebar is now the single source of truth for
# session browsing/loading/exporting. The standalone /sessions list
# was a tabular duplicate. Don't probe it here — a 404 is expected.
NEW_PAGES=( /connectors /jobs /approvals /memory /notifications /api-keys /audit /activity /settings )
ALL_OK=true
for path in "${NEW_PAGES[@]}"; do
  CODE=$(curl $CURL_K -s -o /dev/null -w '%{http_code}' "${AGENT_BASE}${path}" 2>&1)
  if [[ "$CODE" == "404" || "$CODE" == "500" ]]; then
    ALL_OK=false
    fail "T11.2 ${path}" "HTTP $CODE"
  fi
done
if [[ "$ALL_OK" == "true" ]]; then
  pass "T11.2 admin pages reachable (10 routes, no 404/500)"
fi

# T11.3 — A2UI endpoints are gone. Hitting any /api/a2ui/* on the
# agent or /api/v1/ui/* on the MCP must NOT 200. (404 or 502 = good;
# 200 means we forgot to delete a route.)
A2UI_GONE=true
for path in /api/a2ui/manifest /api/a2ui/v0_8/manifest; do
  CODE=$(curl $CURL_K -s -o /dev/null -w '%{http_code}' "${AGENT_BASE}${path}" 2>&1)
  if [[ "$CODE" == "200" ]]; then
    A2UI_GONE=false
    fail "T11.3 ${path}" "still 200 — A2UI route not removed"
  fi
done
MCP_UI_CODE=$(curl $CURL_K -s -o /dev/null -w '%{http_code}' \
  -H "Authorization: Bearer ${MCP_TOKEN}" \
  "${MCP_BASE}/api/v1/ui/manifest" 2>&1)
if [[ "$MCP_UI_CODE" == "200" ]]; then
  A2UI_GONE=false
  fail "T11.3 mcp /api/v1/ui/manifest" "still 200 — MCP UI routes not removed"
fi
if [[ "$A2UI_GONE" == "true" ]]; then
  pass "T11.3 A2UI endpoints removed (agent + MCP)"
fi

# ────────────────────────────────────────────────────────────────
# Cleanup
# ────────────────────────────────────────────────────────────────

section "Cleanup"

if [[ -n "${SESSION_ID:-}" ]]; then
  CLEANUP=$(mcp_curl DELETE "/api/v1/sessions/${SESSION_ID}")
  CLEANUP_CODE="${CLEANUP%%:*}"
  if [[ "$CLEANUP_CODE" == "200" ]]; then
    pass "removed smoke-test session"
  else
    fail "smoke-test session cleanup" "HTTP $CLEANUP_CODE"
  fi
fi

CLEANUP_MEM=$(mcp_curl DELETE "/api/v1/memories/by-key/smoke-test-host?scope=agent")
CLEANUP_MEM_CODE="${CLEANUP_MEM%%:*}"
if [[ "$CLEANUP_MEM_CODE" == "200" ]]; then
  pass "removed smoke-test memory"
elif [[ "$CLEANUP_MEM_CODE" == "404" ]]; then
  skip "smoke-test memory cleanup" "already removed"
else
  fail "smoke-test memory cleanup" "HTTP $CLEANUP_MEM_CODE"
fi

# ────────────────────────────────────────────────────────────────
# Final report
# ────────────────────────────────────────────────────────────────

TOTAL=$((PASSED + FAILED + SKIPPED))
printf "\n${C_BOLD}━━━ Summary ━━━${C_RESET}\n"
printf "  Total checks : %d\n" "$TOTAL"
printf "  ${C_PASS}Passed       : %d${C_RESET}\n" "$PASSED"
printf "  ${C_WARN}Skipped      : %d${C_RESET}\n" "$SKIPPED"
printf "  ${C_FAIL}Failed       : %d${C_RESET}\n" "$FAILED"

if [[ "$FAILED" -gt 0 ]]; then
  printf "\n${C_FAIL}${C_BOLD}Failures:${C_RESET}\n"
  for f in "${FAILURES[@]}"; do
    printf "  • %s\n" "$f"
  done
  exit 1
fi

exit 0
