#!/usr/bin/env python3
"""Okta-only canary: drive `phantom_create_data_worker` via the xlog
connector's MCP (NOT direct UDP), then verify XDM landing via the XSIAM
connector's MCP. Runs INSIDE phantom-vm via:

    docker exec -i phantom_agent python3 < e2e_okta_via_mcp_tool.py

Hard-coded inputs (lifts the per-VM coupling so the script is one self-
contained file):

  - Okta YAML's `fields[]` shape, filtered to top-level composites only
  - vendor + product to drive broker routing → okta_okta_raw
  - destination = udp:10.10.0.8:514 (broker on phantom-vm)

Diagnostic axis: does the OverrideSender path (schema_override → records
generated by `generate_records_with_override` → CEF-wrapped → broker)
land in XDM at all? Compare to direct-UDP smoke (e2e_batch12 = 10 XDM)
to identify gaps in the MCP-tool path.

Known suspected gap: `_generate_value` doesn't handle `type: json`, so
composite fields like `actor` get a random string instead of a nested
JSON-string-shaped value, breaking the MR's `json_extract_scalar` path.
"""

from __future__ import annotations

import json
import os
import time
import urllib.request
import uuid

# Going through the AGENT's embedded MCP (port 8080 loopback inside the
# phantom_agent container) — NOT the per-instance connector's MCP. The
# agent's MCP has `get_xlog_url` populated in its lifespan context
# (bundles/spark/mcp/src/service/phantom_mcp/server.py line 79) and
# bridges to xlog via the agent's own client. Per-instance connector
# containers lack that key (currently a gap to fix in
# phantom-connector-runtime).
#
# Per `bundles/spark/mcp/CLAUDE.md`, the agent registers ~80 tools
# directly via `mcp.tool()(module.fn)`. Tool names DO carry the
# `phantom_` prefix at this layer.
AGENT_MCP = "https://localhost:8080/api/v1/stream/mcp"
XLOG_MCP = AGENT_MCP  # use agent's MCP — phantom_create_data_worker fixed end-to-end as of v0.17.78
# xsiam connector still has the Pydantic-model-wrap gap (tracked in v0.17.78
# CHANGELOG follow-on). Workaround until fixed: hit the XSIAM connector's
# MCP directly via container DNS, which accepts the legacy {request: ...}
# nested shape that batch 12 proved.
XSIAM_MCP = "http://phantom-connector-xsiam-Cortex_XSIAM:9000/mcp"
TOKEN = os.environ["MCP_TOKEN"]

# Disable SSL verification — agent's MCP uses self-signed loopback cert.
import ssl as _ssl
_SSL_CTX = _ssl.create_default_context()
_SSL_CTX.check_hostname = False
_SSL_CTX.verify_mode = _ssl.CERT_NONE

# Okta top-level field shape — pulled from the bundled
# Okta__OktaModelingRules_2_0__okta_okta_raw/data_source.yaml. The
# dotted-key leaves are intentionally NOT included; the MR reads the
# composites and json_extract_scalars from inside.
OKTA_FIELDS = [
    {"name": "actor", "type": "json"},
    {"name": "authenticationContext", "type": "json"},
    {"name": "client", "type": "json"},
    {"name": "debugContext", "type": "json"},
    {"name": "displayMessage", "type": "string_long"},
    {"name": "eventType", "type": "string_short"},
    {"name": "legacyEventType", "type": "string_short"},
    {"name": "outcome", "type": "json"},
    {"name": "published", "type": "datetime"},
    {"name": "request", "type": "json"},
    {"name": "securityContext", "type": "json"},
    {"name": "severity", "type": "enum"},
    {"name": "target", "type": "json", "is_array": True},
    {"name": "transaction", "type": "json"},
    {"name": "uuid", "type": "string_short"},
    {"name": "version", "type": "string_short"},
]


def post(url, body, sid=None):
    h = {"Authorization": f"Bearer {TOKEN}", "Content-Type": "application/json",
         "Accept": "application/json, text/event-stream"}
    if sid:
        h["mcp-session-id"] = sid
    req = urllib.request.Request(url, data=json.dumps(body).encode(),
                                 headers=h, method="POST")
    with urllib.request.urlopen(req, timeout=180, context=_SSL_CTX) as r:
        return r.read().decode(), r.headers


def sse_parse(text):
    for ln in text.split("\n"):
        if ln.startswith("data:"):
            try:
                f = json.loads(ln[5:].strip())
                if "result" in f:
                    c = f["result"].get("content", [])
                    if c:
                        return json.loads(c[0].get("text", "{}"))
                if "error" in f:
                    return {"_err": f["error"]}
            except Exception:
                pass
    return {}


def open_session(url):
    body, hdrs = post(url, {"jsonrpc": "2.0", "id": 1, "method": "initialize",
                            "params": {"protocolVersion": "2024-11-05",
                                       "capabilities": {},
                                       "clientInfo": {"name": "smk", "version": "1"}}})
    sid = hdrs.get("mcp-session-id") or hdrs.get("Mcp-Session-Id")
    post(url, {"jsonrpc": "2.0", "method": "notifications/initialized", "params": {}}, sid)
    return sid


def call(url, sid, name, args, rid=99, debug=False):
    body, _ = post(url, {"jsonrpc": "2.0", "id": rid, "method": "tools/call",
                         "params": {"name": name, "arguments": args}}, sid)
    if debug:
        print(f"  [debug] raw SSE for {name}: {body[:1500]}")
    return sse_parse(body)


# ───────────────────────────────────────────────────────────────────
batch = int(time.time())
marker = f"mcp-okta-{batch}-{uuid.uuid4().hex[:6]}"
worker_name = f"smk-okta-mcp-{batch}"

print(f"BATCH={batch} MARKER={marker}")
print(f"worker={worker_name}")
print()

# Step 1 — fire phantom_create_data_worker via xlog connector MCP
xlog_sid = open_session(XLOG_MCP)
print(f"xlog MCP session: {xlog_sid}")

# Pydantic-model fields are FLATTENED at the agent's proxy layer — pass
# them at top level, NOT wrapped in {"request": {...}}. Otherwise the
# validator raises "Unexpected keyword argument" on `request`.
create_args = {
    "name": worker_name,
    "type": "CEF",
    "destination": "udp:10.10.0.8:514",
    "count": 3,
    "interval": 2,
    "vendor": "okta",
    "product": "okta",
    "version": "1.0",
    "schema_override": OKTA_FIELDS,
    # Pass a `uuid` observable override so the MR's xdm.event.id
    # (which Okta MR populates from uuid) carries our marker.
    "observables_dict": {"uuid": [marker]},
}
res = call(XLOG_MCP, xlog_sid, "phantom_create_data_worker", create_args, rid=10, debug=True)
print(f"createDataWorker result: {json.dumps(res, default=str)[:500]}")
if isinstance(res, dict) and res.get("_err"):
    print(f"\n❌ createDataWorker error: {res['_err']}")
    raise SystemExit(2)

# Step 2 — wait for ticks + ingest
print("\nWaiting 120s for ticks + XSIAM ingest...")
for i in range(4):
    time.sleep(30)
    print(f"  +{(i + 1) * 30}s")

# Step 3 — query via XSIAM connector MCP
xsiam_sid = open_session(XSIAM_MCP)
print(f"xsiam MCP session: {xsiam_sid}")

# Raw landing — what columns made it onto the wire and into the raw dataset?
raw_q = (
    'dataset = okta_okta_raw '
    f'| filter _raw_log contains "{marker}" '
    '| limit 3'
)
raw = call(XSIAM_MCP, xsiam_sid, "run_xql_query",
           {"request": {"query": raw_q, "tenant_timeframe": {"relativeTime": 1800000}}},
           rid=20)
rr = (raw or {}).get("reply", {}) or {}
print(f"\nRAW landing: status={rr.get('status')}, n={rr.get('number_of_results', 0)}")
if rr.get("status") == "SUCCESS" and rr.get("number_of_results", 0) > 0:
    sample = rr["results"]["data"][0]
    raw_cols = {k: str(v)[:80] for k, v in sample.items()
                if v not in (None, "", "null") and not k.startswith("_")}
    print(f"  raw cols populated: {len(raw_cols)}")
    for k in sorted(raw_cols)[:8]:
        print(f"    {k:30} = {raw_cols[k]}")

# XDM materialization
dm_q = (
    'datamodel dataset = okta_okta_raw '
    f'| filter xdm.event.id contains "{marker}" '
    '| fields xdm.* | limit 1'
)
dm = call(XSIAM_MCP, xsiam_sid, "run_xql_query",
          {"request": {"query": dm_q, "tenant_timeframe": {"relativeTime": 1800000}}},
          rid=30)
dr = (dm or {}).get("reply", {}) or {}
print(f"\nXDM materialization: status={dr.get('status')}, n={dr.get('number_of_results', 0)}")
if dr.get("status") == "SUCCESS" and dr.get("number_of_results", 0) > 0:
    row = dr["results"]["data"][0]
    populated = {k: v for k, v in row.items()
                 if v not in (None, "", "null") and k.startswith("xdm.")}
    print(f"\n✅ XDM populated: {len(populated)} fields")
    for k in sorted(populated):
        print(f"  {k:42} = {str(populated[k])[:75]}")
else:
    print("\n❌ no XDM by marker — diagnostic gap somewhere in the MCP-tool path")

# Step 4 — list + kill the worker
lw = call(XLOG_MCP, xlog_sid, "phantom_list_workers", {}, rid=40)
wid = None
if isinstance(lw, list):
    for w in lw:
        if isinstance(w, dict) and w.get("name") == worker_name:
            wid = w.get("worker")
            break
print(f"\nworker UUID: {wid}")
if wid:
    kill = call(XLOG_MCP, xlog_sid, "phantom_kill_worker",
                {"worker_id": wid}, rid=50)
    print(f"kill: {json.dumps(kill, default=str)[:200]}")
