#!/usr/bin/env bash
# Guardian — first-time install / upgrade script.
#
# Reads GUARDIAN_REGISTRY_USER + GUARDIAN_REGISTRY_TOKEN from .env, logs
# into ghcr.io, pulls the pinned image versions for the three Guardian
# services, and brings the stack up. After this completes, open
# https://localhost:3000 in a browser, sign in with the default
# credentials (admin / value of GUARDIAN_DEFAULT_ADMIN_PASSWORD from
# .env — v0.5.5+: random per-install, the script generates + writes
# it for you if missing) and change the password at /profile on
# first login.
#
# Idempotent — safe to re-run for upgrades. The docker login step
# refreshes cached creds; docker compose pull picks up any newer
# images that match the pinned version tags in docker-compose.yml.

set -euo pipefail

cd "$(dirname "$0")"

# ─── Pre-flight: required tools ───────────────────────────────────────
need() {
  command -v "$1" >/dev/null 2>&1 || {
    echo "ERROR: '$1' not found in PATH. Install it and re-run." >&2
    exit 1
  }
}
need docker
# `docker compose` (v2 plugin) is preferred over the legacy `docker-compose`.
# Verify the v2 plugin is installed.
if ! docker compose version >/dev/null 2>&1; then
  echo "ERROR: 'docker compose' v2 plugin not available." >&2
  echo "       Install: https://docs.docker.com/compose/install/" >&2
  exit 1
fi

# ─── Pre-flight: .env exists and is readable ──────────────────────────
if [[ ! -f .env ]]; then
  echo "ERROR: .env not found in $(pwd)." >&2
  echo "       Copy .env.example to .env, fill in the values, then re-run." >&2
  echo "       (Suggested: chmod 600 .env after creating it.)" >&2
  exit 1
fi

# .env should not be world-readable — it carries the registry token
# and the encryption KEK. Warn but don't hard-fail (some Linux fs's
# don't preserve mode bits).
PERM=$(stat -c '%a' .env 2>/dev/null || stat -f '%Lp' .env 2>/dev/null || echo "")
if [[ -n "$PERM" && "$PERM" != "600" && "$PERM" != "400" ]]; then
  echo "WARN: .env permissions are $PERM. Recommended: chmod 600 .env" >&2
fi

# ─── Source .env so this script can read the registry creds ──────────
# `set -a` exports every var defined here for child processes. `set +a`
# turns it back off so any `export` keywords later don't leak in. The
# `# shellcheck` disables the "can't follow non-constant source" warn.
set -a
# shellcheck disable=SC1091
source .env
set +a

: "${GUARDIAN_REGISTRY_USER:?GUARDIAN_REGISTRY_USER not set in .env}"
: "${GUARDIAN_REGISTRY_TOKEN:?GUARDIAN_REGISTRY_TOKEN not set in .env}"

if [[ "$GUARDIAN_REGISTRY_TOKEN" == "ghp_REPLACE_WITH_TOKEN_FROM_ONBOARDING" ]]; then
  echo "ERROR: GUARDIAN_REGISTRY_TOKEN is still the placeholder value." >&2
  echo "       Replace it with the real token from your Kite onboarding email." >&2
  exit 1
fi

# Soft-warn on the most common mistakes that will bite later.
if [[ -z "${MCP_TOKEN:-}" ]]; then
  echo "WARN: MCP_TOKEN unset. Generating one would be:" >&2
  echo "      openssl rand -hex 32" >&2
fi
if [[ -z "${GUARDIAN_SECRET_KEK:-}" ]]; then
  echo "WARN: GUARDIAN_SECRET_KEK unset. Operator secrets will be stored as" >&2
  echo "      plaintext on disk. Generate one with: openssl rand -base64 32" >&2
fi

# v0.5.5+ — back-fill GUARDIAN_DEFAULT_ADMIN_PASSWORD if missing. This
# is the bootstrap admin password seeded into SecretStore on first
# boot (the agent forces a change at /profile on first login, so
# this value is only consequential for ONE login). Pre-v0.5.5 it was
# hardcoded in the guardian-agent image; v0.5.5 moves it out so no
# credential is baked anywhere. Generate + write atomically to .env.
if ! grep -q '^GUARDIAN_DEFAULT_ADMIN_PASSWORD=' .env; then
  NEW_DEFAULT_ADMIN_PASSWORD="$(openssl rand -base64 24 | tr -d '\n+/=' | cut -c1-24)"
  {
    echo ""
    echo "# ─── Bootstrap admin password (v0.5.5+) ──────────────────────────────"
    echo "# Auto-generated by install.sh on v0.5.5+ install (or back-filled on"
    echo "# upgrade from pre-v0.5.5). Consumed only when SecretStore is empty"
    echo "# (fresh install OR after guardian-factory-reset). Forced password"
    echo "# change at /profile makes this irrelevant after first login."
    echo "GUARDIAN_DEFAULT_ADMIN_PASSWORD=$NEW_DEFAULT_ADMIN_PASSWORD"
  } >> .env
  chmod 600 .env
  echo "→ Generated GUARDIAN_DEFAULT_ADMIN_PASSWORD (saved to .env)"
  # Re-source so the rest of this script + docker compose see it.
  set -a
  # shellcheck disable=SC1091
  source .env
  set +a
fi

# ─── Step 0.5: Apply digest manifest to .env (v0.3.0+) ────────────────
# The customer compose references each image as @${DIGEST_GUARDIAN_<SVC>}.
# Without these env vars, docker compose fails loudly with a clear hint
# pointing at the bundled release-manifest.env (which lives next to this
# script in the install kit tarball). Mirror what guardian-installer does:
# strip stale GUARDIAN_VERSION + DIGEST_GUARDIAN_* lines, append the
# manifest as a clean block. Idempotent on repeat runs.
if [[ -f release-manifest.env ]]; then
  echo "→ Applying digest manifest to .env"

  # Sanity: every required key must be present.
  for key in GUARDIAN_VERSION DIGEST_GUARDIAN_AGENT \
             DIGEST_GUARDIAN_UPDATER DIGEST_GUARDIAN_BROWSER; do
    if ! grep -q "^${key}=" release-manifest.env; then
      echo "ERROR: release-manifest.env missing required key: $key" >&2
      echo "       The install kit tarball is corrupted; re-download from" >&2
      echo "       https://github.com/kite-production/guardian/releases" >&2
      exit 1
    fi
  done

  # Ensure trailing newline before stripping.
  if [[ -s .env ]] && [[ "$(tail -c 1 .env | xxd -p 2>/dev/null)" != "0a" ]]; then
    printf '\n' >> .env
  fi

  # Strip stale manifest-managed lines AND the comment header block we
  # emit alongside them (v0.5.4 — pre-v0.5.4 only the value lines were
  # stripped, so every re-run accumulated a fresh comment block while
  # the value lines correctly rotated). Patterns mirror the ones in
  # guardian-installer.template.sh so a .env that's bounced between
  # both installer flavors gets cleaned the same way.
  sed -i.bak \
    -e '/^# ─── Digest manifest (managed by /d' \
    -e '/^# DO NOT EDIT BY HAND\./d' \
    -e '/^# strips and rewrites these lines/d' \
    -e "/^# version, download that version's guardian-installer/d" \
    -e '/^# these lines as a unit from the bundled/d' \
    -e '/^GUARDIAN_VERSION=/d' \
    -e '/^DIGEST_GUARDIAN_/d' \
    .env
  rm -f .env.bak

  # Collapse consecutive blank lines left behind by the strip.
  awk 'NF || prev_nf { print } { prev_nf = NF }' .env > .env.tmp \
    && mv .env.tmp .env

  # Append the manifest as a labeled block.
  {
    echo ""
    echo "# ─── Digest manifest (managed by install.sh) ──────────────────────"
    echo "# DO NOT EDIT BY HAND. Re-running install.sh strips and rewrites"
    echo "# these lines as a unit from the bundled release-manifest.env."
    cat release-manifest.env
  } >> .env
  chmod 600 .env

  # Re-source so subsequent docker compose pull/up sees the new values
  # in the script's own env (in addition to the file).
  set -a
  # shellcheck disable=SC1091
  source .env
  set +a

  echo "✓ Digest manifest applied"
else
  echo "WARN: release-manifest.env not found in $(pwd)." >&2
  echo "      v0.3.0+ install kits include this file. If you're upgrading" >&2
  echo "      a v0.2.x install, your tarball is older than v0.3.0 — download" >&2
  echo "      a fresh kit from the GitHub Release for the version you want." >&2
fi

# ─── Step 1: docker login ─────────────────────────────────────────────
echo "→ Logging in to ghcr.io as $GUARDIAN_REGISTRY_USER"
# --password-stdin keeps the token out of `ps` output AND out of any
# shell history that might log argv.
echo "$GUARDIAN_REGISTRY_TOKEN" \
  | docker login ghcr.io -u "$GUARDIAN_REGISTRY_USER" --password-stdin

# ─── Step 2: pull pinned images ───────────────────────────────────────
echo "→ Pulling pinned images (this can take a few minutes on first install)"
docker compose pull

# ─── Step 3: bring the stack up ───────────────────────────────────────
echo "→ Starting Guardian stack"
docker compose up -d --remove-orphans

# ─── Step 4: wait for guardian-agent to become healthy ─────────────────
echo "→ Waiting for guardian-agent to become healthy (up to ~3 minutes)…"
ATTEMPTS=40
status="starting"
for ((attempt = 1; attempt <= ATTEMPTS; attempt++)); do
  status=$(docker inspect -f '{{.State.Health.Status}}' guardian_agent 2>/dev/null || echo missing)
  if [[ "$status" == "healthy" ]]; then
    break
  fi
  if [[ "$status" == "unhealthy" ]]; then
    echo "  guardian-agent reported unhealthy on attempt $attempt — recent logs:" >&2
    docker compose logs --tail 30 guardian-agent >&2 || true
  fi
  sleep 5
done

if [[ "$status" != "healthy" ]]; then
  echo "" >&2
  echo "ERROR: guardian-agent did not become healthy within $((ATTEMPTS * 5))s." >&2
  echo "       Diagnostic commands:" >&2
  echo "         docker compose ps" >&2
  echo "         docker compose logs guardian-agent" >&2
  echo "         docker compose logs guardian-updater" >&2
  exit 1
fi

# (Multi-file kit's install.sh runs from the dir it was extracted
# to, so the script is already persisted in place — no self-copy
# needed. The single-binary guardian-installer self-installs into
# $INSTALL_DIR/ at the end of its run; see installer/guardian-installer
# .template.sh's "Self-install" step. guardian-factory-reset finds
# either via $INSTALL_DIR/guardian-installer{,-dev} or just calls
# install.sh in place when running against a kit install.)

# ─── Step 5: tell the operator what to do next ────────────────────────
echo ""
echo "✓ Guardian is running."
echo ""
echo "  UI:                 https://localhost:3000"
echo "                      Browser will warn on the self-signed cert;"
echo "                      accept it to proceed."
echo ""
echo "  First-time login:"
echo "                      username:  admin"
echo "                      password:  ${GUARDIAN_DEFAULT_ADMIN_PASSWORD}"
echo ""
echo "                      v0.5.5+ — the password above is randomly"
echo "                      generated per install (no credential is baked"
echo "                      into any image). It also lives in this .env"
echo "                      under GUARDIAN_DEFAULT_ADMIN_PASSWORD if you"
echo "                      need to retrieve it after closing this terminal."
echo ""
echo "                      The UI will prompt you to change the password"
echo "                      at /profile on first login. Do that, then sign"
echo "                      in again with the new credentials. After that,"
echo "                      the value above is never consulted again — your"
echo "                      operator-set password lives encrypted in"
echo "                      SecretStore (GUARDIAN_SECRET_KEK protects it)."
echo ""
echo "  Forgot password?    sudo ./guardian-reset-admin-password"
echo "                      (host wrapper — execs into guardian_agent and"
echo "                      runs the in-container reset CLI with masked"
echo "                      stdin. Same audit trail as a /profile change.)"
echo ""
echo "  Factory reset?      sudo ./guardian-factory-reset"
echo "                      (wipes all operator state — memories, instances,"
echo "                      API keys, audit log, sessions, jobs; preserves"
echo "                      .env + KEK so re-install brings stack back up"
echo "                      with the same registry credentials. Re-runs the"
echo "                      installer at the end. --yes skips the confirmation"
echo "                      prompt, --dry-run shows the plan without wiping.)"
echo ""
echo "  Logs:               docker compose logs -f guardian-agent"
echo "  Stop:               docker compose down"
echo "  Upgrade:            Download a newer install kit (each kit is sealed"
echo "                      to one version), extract, and run ./install.sh"
echo "                      from the new directory. Or use the in-app updater"
echo "                      in the agent UI sidebar (no manual download)."
echo ""
